// enrich-scholarship-content
//
// Fills the SOFT descriptive fields on a scholarship row that are
// commonly null after a basic scrape but heavily used by the brief +
// counselor + Discover Strategy tab for decision-grade context:
//
//   Decision-supporting (the "should I apply?" answer):
//   · why_this_fits             — who this is a strong fit for
//   · ideal_candidate_profile   — typical successful applicant
//   · how_to_win                — real angle to lead with
//   · what_to_prepare_first     — first concrete deliverable
//   · best_for_tags             — 3-5 short audience tags
//
//   Decision-PROTECTING (the "don't waste 20 hours on this" warnings):
//   · common_rejection_reasons  — specific failure patterns
//   · weak_candidate_warning    — honest gates: when to skip applying
//   · strategy_notes            — tactical insider knowledge
//
// These are SOFT fields — descriptive, not factual. Generated by AI
// (pro tier — these are written ONCE per scholarship and cached forever,
// so quality > cost). The prompt explicitly tells the model to OMIT a
// field rather than fill it with platitudes — generic copy is worse
// than nothing on the user-facing Strategy tab.
//
// Hard rule: only writes fields that are CURRENTLY NULL/empty. Never
// overwrites an existing value (whether human-curated or previously
// AI-filled). Idempotent: repeat invocations are no-ops.
//
// Used by:
//   · /admin/scholarships-verification "Fill missing content" button
//   · enrich-scholarships-content-cron daily batch backfill
//
// Auth: admin or service-role only.

import { chatCompletions } from "../_shared/ai-gateway.ts";
import { requireAdminOrService } from "../_shared/auth.ts";
import { EDITORIAL_RULES_TIGHT } from "../_shared/editorial-rules.ts";
import { CORS_HEADERS_BASIC as corsHeaders, handleCorsOptions } from "../_shared/cors.ts";
import { respondJson } from "../_shared/http.ts";
import { createServiceClient } from "../_shared/clients.ts";

const json = (status: number, body: unknown) =>
  respondJson(status, body, corsHeaders);

const COST_ESTIMATE_USD = 0.005;

interface EnrichmentOutput {
  why_this_fits?: string;
  ideal_candidate_profile?: string;
  how_to_win?: string;
  what_to_prepare_first?: string;
  best_for_tags?: string[];
  common_rejection_reasons?: string;
  weak_candidate_warning?: string;
  strategy_notes?: string;
}

/* Schema lives in JSON-document form so the LLM can ground each field
 * against its description. The three trust-telling fields at the bottom
 * (common_rejection_reasons, weak_candidate_warning, strategy_notes)
 * are the most decision-critical for the user's "should I apply?"
 * question and were previously left null on every row. They're what a
 * real admissions counselor would tell a student before they spend
 * 20 hours on an essay — adding them is the difference between a
 * scholarship database that's polite and one that's actually useful. */
const SCHEMA_DOC = `{
  "why_this_fits": "string — 1-2 sentences naming who this is a strong fit for. Specific (not 'great students') — refer to field, level, geography",
  "ideal_candidate_profile": "string — 1-2 sentences sketching the typical successful applicant: numbers, background, what they've already done",
  "how_to_win": "string — 1-2 sentences of strategic application advice specific to THIS program. Name a real angle, not 'write a strong essay'",
  "what_to_prepare_first": "string — single sentence: the first concrete document or action to start with",
  "best_for_tags": "array of 2-4 SPECIFIC kebab-case tags. STRICT ALLOWLIST: subject areas (e.g. 'computer-science','public-policy','public-health','stem','engineering','business','law','arts','medicine','climate-change','agriculture') and SPECIFIC cohort markers (e.g. 'financial-need','mid-career','early-career','women-in-stem','refugee-status','non-eu','first-generation','displaced-students'). BANNED — do NOT output any of these: any country/region/city ('africa-focus','europe','germany','uk-study'), any degree level ('undergrad','phd','masters'), any coverage tag ('full-ride','partial'), any generic descriptor ('international','academic-excellence','leadership','innovation','development','community-impact','cross-cultural','all-fields','higher-education','professional-development','research','scholarship'), any duration ('3-5-years'). If a tag would be generic or boilerplate, OMIT IT — fewer specific tags beats more vague ones",
  "common_rejection_reasons": "string — 1-2 sentences naming the SPECIFIC reasons strong-on-paper applicants get rejected from this program. NOT generic ('unclear essays'). Real ('thesis lacks measurable impact', 'recommenders too senior, not actual collaborators', 'no demonstrated tie to host country before applying'). Skip this field rather than write generic copy",
  "weak_candidate_warning": "string — 1-2 sentences naming the profile signals that mean a student should NOT apply (would waste their effort). Honest gating: GPA below threshold, missing required experience, citizenship gaps, level mismatch. Specific. Skip rather than soften",
  "strategy_notes": "string — 1-2 sentences of higher-order tactical insight that doesn't fit elsewhere. Application timing pattern, recommender selection, narrative thread, anything genuinely insider. Skip rather than fill with platitudes"
}`;

function isolateJson(raw: string): string {
  let s = raw.trim().replace(/^```(?:json)?\s*/i, "").replace(/```\s*$/i, "").trim();
  const first = s.indexOf("{");
  const last = s.lastIndexOf("}");
  if (first !== -1 && last !== -1 && last > first) s = s.slice(first, last + 1);
  return s;
}

Deno.serve(async (req) => {
  const pre = handleCorsOptions(req);
  if (pre) return pre;
  if (req.method !== "POST") return json(405, { error: "POST only" });

  const auth = await requireAdminOrService(req);
  if (!auth.ok) return json(401, { error: `Unauthorized: ${auth.reason}` });

  let body: { scholarship_id?: string };
  try { body = await req.json(); }
  catch { return json(400, { error: "Invalid JSON body" }); }
  if (!body.scholarship_id) return json(400, { error: "scholarship_id required" });

  const supa = createServiceClient();

  const { data: row, error: loadErr } = await supa
    .from("scholarships")
    .select(
      `scholarship_id, scholarship_name, provider_name, host_country, coverage_type, award_amount_text, target_degree_level, target_fields, eligibility_requirements, citizenship_requirements, min_gpa, gpa_scale, min_ielts, min_toefl, min_sat, essay_required, interview_required, recommendation_letters_required, selectivity_level, why_this_fits, ideal_candidate_profile, how_to_win, what_to_prepare_first, best_for_tags, common_rejection_reasons, weak_candidate_warning, strategy_notes`
    )
    .eq("scholarship_id", body.scholarship_id)
    .maybeSingle();

  if (loadErr || !row) return json(404, { error: "Scholarship not found" });

  // Identify which soft fields are missing — those are the only ones we'll
  // attempt to fill. If everything is populated we no-op cleanly.
  const missing: string[] = [];
  if (!row.why_this_fits)             missing.push("why_this_fits");
  if (!row.ideal_candidate_profile)   missing.push("ideal_candidate_profile");
  if (!row.how_to_win)                missing.push("how_to_win");
  if (!row.what_to_prepare_first)     missing.push("what_to_prepare_first");
  if (!Array.isArray(row.best_for_tags) || row.best_for_tags.length === 0) missing.push("best_for_tags");
  if (!row.common_rejection_reasons)  missing.push("common_rejection_reasons");
  if (!row.weak_candidate_warning)    missing.push("weak_candidate_warning");
  if (!row.strategy_notes)            missing.push("strategy_notes");

  if (missing.length === 0) {
    return json(200, { ok: true, scholarship_id: row.scholarship_id, status: "already_full", filled: [] });
  }

  const facts = [
    `Name: ${row.scholarship_name}`,
    `Provider: ${row.provider_name ?? "—"}`,
    `Host country: ${row.host_country ?? "—"}`,
    `Coverage: ${row.coverage_type}${row.award_amount_text ? ` (${row.award_amount_text})` : ""}`,
    `Levels: ${(row.target_degree_level ?? []).join(", ") || "—"}`,
    `Fields: ${(row.target_fields ?? []).join(", ") || "—"}`,
    `Selectivity: ${row.selectivity_level ?? "unknown"}`,
    `Min GPA: ${row.min_gpa ?? "—"}${row.gpa_scale ? `/${row.gpa_scale}` : ""}`,
    `Min IELTS: ${row.min_ielts ?? "—"}`,
    `Min TOEFL: ${row.min_toefl ?? "—"}`,
    `Min SAT: ${row.min_sat ?? "—"}`,
    `Essay required: ${row.essay_required ?? "unknown"}`,
    `Interview required: ${row.interview_required ?? "unknown"}`,
    `Rec letters: ${row.recommendation_letters_required ?? "unknown"}`,
    `Eligibility prose: ${row.eligibility_requirements ?? "—"}`,
    `Citizenship: ${row.citizenship_requirements ?? "—"}`,
  ].join("\n");

  const prompt = `You write the strategy notes a real admissions counselor would give a student trying to decide whether to apply to this specific scholarship. Output ONLY a JSON object matching the schema. No markdown fences. No preamble.

CONTEXT — what these fields are FOR:
The user-facing Discover page renders these on a "Strategy" tab inside the scholarship detail. A student reads them to decide: "Should I spend 20 hours writing this application or skip it and focus elsewhere?" Generic copy WASTES their time. Specific copy SAVES it.

QUALITY BAR — these rules are not optional:
1. Use ONLY publicly known facts about the scholarship's general structure (which audience it targets, what it values, application timing patterns). Do NOT invent specific deadlines, dollar amounts, or unique program features beyond what's in the FACTS block.
2. Avoid superlatives — "the best", "world-class", "highly prestigious", "incredibly competitive". They tell the student nothing.
3. Avoid platitudes — "write a strong essay", "showcase your strengths", "be authentic", "stand out". A counselor would never say these.
4. why_this_fits must NAME the audience ("African policy professionals re-entering academia", "STEM PhDs targeting EU labs"), never "ambitious students" / "strong applicants".
5. how_to_win must name a REAL ANGLE — a thesis shape, a recommender pattern, a story type, a timing move. Examples of good: "Lead with a measurable social-impact thesis you can show 6 months of evidence on; weakest essays are aspirational without traction." Examples of BAD: "Write a compelling personal statement." If you can't name a real angle, skip the field.
6. common_rejection_reasons must name SPECIFIC failure patterns — "essays read as lists of accomplishments rather than a single thread", "recommenders too senior to speak to actual collaboration", "no demonstrated tie to host country prior to applying". NOT "unclear writing" or "weak applications". Skip if you can't be specific.
7. weak_candidate_warning must name HONEST GATES — GPA / language-test / citizenship / level / experience thresholds where applying is wasted effort. Be willing to disqualify. Example: "Skip if your GPA is below 3.6/4.0 — the rejection rate at that band is near total." If you can't be honest, skip.
8. strategy_notes is for tactical insider knowledge — application timing windows, recommender selection patterns, narrative threads that work. Skip rather than fill with platitudes.
9. Apply the canonical editorial rules:
${EDITORIAL_RULES_TIGHT}
10. NEVER write user-relative phrasing. The reader's nationality, location, current school, family situation are UNKNOWN. Banned phrases include: "without leaving the country", "your home country", "back home", "for students like you", "in your situation", "given your background", "international students like yourself", "applicants from your region". The text is read by visitors from anywhere — write program-relative not reader-relative copy. If a fact is true ABOUT the scholarship (e.g. "fully English-medium so applicants don't need to relocate for language reasons"), state it neutrally.
11. SKIP > FLUFF. If you cannot say something specific and useful, OMIT the field. The schema treats missing fields as acceptable; generic content is worse than nothing.
12. Output language: English.

SCHEMA:
${SCHEMA_DOC}

FACTS:
${facts}

MISSING fields you must fill (skip the others — and skip any of these you cannot fill specifically):
${missing.join(", ")}

Output the JSON now.`;

  let parsed: EnrichmentOutput;
  try {
    // Pro tier — these fields are written ONCE per scholarship and cached
    // forever. Going from flash (~$0.0008) to pro (~$0.005) is ~$1 total
    // across the whole catalogue and the difference between generic copy
    // and counsellor-grade strategy notes is the entire value prop of
    // the Strategy tab. Worth every cent.
    const resp = await chatCompletions({
      tier: "pro",
      messages: [
        { role: "system", content: "You are a Yale/Cambridge/Harvard-trained admissions strategist writing for a verified scholarship database. Output only valid JSON matching the requested schema. Each field tells a real student whether to spend 20 hours on this application — generic content WASTES their time. Skip a field rather than fill it with platitudes." },
        { role: "user", content: prompt },
      ],
      stream: false,
    });
    if (!resp.ok) {
      const t = await resp.text();
      console.error("[enrich-scholarship-content] gateway error", resp.status, t.slice(0, 300));
      return json(502, { error: "Generation failed" });
    }
    const data = await resp.json();
    const raw = (
      data?.choices?.[0]?.message?.content
      ?? (Array.isArray(data?.content) ? data.content.map((c: any) => c?.text ?? "").join("") : "")
      ?? ""
    ) as string;
    if (!raw) return json(502, { error: "Empty completion" });
    parsed = JSON.parse(isolateJson(raw)) as EnrichmentOutput;
  } catch (e) {
    console.warn("[enrich-scholarship-content] parse failed", (e as Error).message);
    return json(502, { error: "Parse failed" });
  }

  // Build the patch — only set fields that were missing AND that the AI returned.
  const patch: Record<string, unknown> = {};
  const filled: string[] = [];

  if (missing.includes("why_this_fits") && typeof parsed.why_this_fits === "string" && parsed.why_this_fits.length > 20) {
    patch.why_this_fits = parsed.why_this_fits.slice(0, 400);
    filled.push("why_this_fits");
  }
  if (missing.includes("ideal_candidate_profile") && typeof parsed.ideal_candidate_profile === "string" && parsed.ideal_candidate_profile.length > 20) {
    patch.ideal_candidate_profile = parsed.ideal_candidate_profile.slice(0, 400);
    filled.push("ideal_candidate_profile");
  }
  if (missing.includes("how_to_win") && typeof parsed.how_to_win === "string" && parsed.how_to_win.length > 20) {
    patch.how_to_win = parsed.how_to_win.slice(0, 400);
    filled.push("how_to_win");
  }
  if (missing.includes("what_to_prepare_first") && typeof parsed.what_to_prepare_first === "string" && parsed.what_to_prepare_first.length > 10) {
    patch.what_to_prepare_first = parsed.what_to_prepare_first.slice(0, 240);
    filled.push("what_to_prepare_first");
  }
  if (missing.includes("best_for_tags") && Array.isArray(parsed.best_for_tags)) {
    const tags = parsed.best_for_tags
      .filter((t: unknown): t is string => typeof t === "string" && t.length > 2 && t.length < 30)
      .slice(0, 6);
    if (tags.length >= 2) {
      patch.best_for_tags = tags;
      filled.push("best_for_tags");
    }
  }
  // The three trust-telling fields. Floor of 30 chars (a single
  // generic-sounding sentence is ~25 chars; we want at least one
  // substantive clause). Ceiling of 500 chars for storage hygiene. The
  // model is instructed to OMIT these rather than write generic copy,
  // so we trust missing > present-but-weak.
  if (missing.includes("common_rejection_reasons") && typeof parsed.common_rejection_reasons === "string" && parsed.common_rejection_reasons.length > 30) {
    patch.common_rejection_reasons = parsed.common_rejection_reasons.slice(0, 500);
    filled.push("common_rejection_reasons");
  }
  if (missing.includes("weak_candidate_warning") && typeof parsed.weak_candidate_warning === "string" && parsed.weak_candidate_warning.length > 30) {
    patch.weak_candidate_warning = parsed.weak_candidate_warning.slice(0, 500);
    filled.push("weak_candidate_warning");
  }
  if (missing.includes("strategy_notes") && typeof parsed.strategy_notes === "string" && parsed.strategy_notes.length > 30) {
    patch.strategy_notes = parsed.strategy_notes.slice(0, 500);
    filled.push("strategy_notes");
  }

  if (filled.length === 0) {
    return json(200, { ok: false, scholarship_id: row.scholarship_id, status: "no_valid_output", filled: [] });
  }

  // Clear the embedding so embed-scholarships re-runs and the new soft text
  // becomes part of the search corpus.
  patch.embedding = null;
  patch.embedded_at = null;

  await supa.from("scholarships").update(patch as never).eq("scholarship_id", row.scholarship_id);

  return json(200, {
    ok: true,
    scholarship_id: row.scholarship_id,
    status: "filled",
    filled,
    cost_estimate_usd: COST_ESTIMATE_USD,
  });
});
