/**
 * Per-scholarship personalized deep-dive payload.
 *
 * Generated by the scholarship-deep-dive edge function and rendered by
 * <ScholarshipDeepDive />. Cached server-side keyed on (scholarship_id ×
 * profile_hash) so re-visits are free.
 *
 * Keep this in sync with the SCHEMA_DOC inside the edge function.
 * SCHEMA_VERSION (server) bumps when shape changes — old cached rows
 * with a lower version are regenerated on first read.
 */

export type DeepDiveBreakdownStatus = "met" | "near" | "miss" | "unknown";

export interface DeepDiveBreakdownItem {
  label: string;       // e.g. "GPA threshold"
  status: DeepDiveBreakdownStatus;
  detail: string;      // e.g. "Yours 3.7/4.0 vs required 3.5"
}

export interface DeepDiveMatch {
  /** Honest 0-100 fit score, computed by the AI given profile vs requirements. */
  overall_score: number;
  breakdown: DeepDiveBreakdownItem[];
}

export interface DeepDiveStrategy {
  /** Single-line positioning angle the student should lead with for THIS scholarship. */
  headline: string;
  /** 3-5 specific tactical moves anchored to the student's background. */
  points: string[];
  /** 0-2 things NOT to do, given the student's profile. */
  avoid: string[];
}

export type DeepDiveOddsBucket = "primary" | "competitive" | "stretch";

export interface DeepDiveOdds {
  bucket: DeepDiveOddsBucket;
  /** 1-2 sentences citing the gap or alignment. */
  rationale: string;
  /** One line on what the typical successful applicant looks like. */
  typical_admit_profile: string;
}

export interface DeepDiveThirtyDayItem {
  week: 1 | 2 | 3 | 4;
  action: string;
}

export interface DeepDiveThirtyDay {
  items: DeepDiveThirtyDayItem[];
}

export interface ScholarshipDeepDiveData {
  match: DeepDiveMatch;
  strategy: DeepDiveStrategy;
  odds: DeepDiveOdds;
  thirty_day: DeepDiveThirtyDay;
  /** Server metadata — included on every response. Optional in the
   *  pre-fetch / loading state. */
  _cached?: boolean;
  _generated_at?: string;
}
