/**
 * SharedBrief — public viewer for a shared TopUni AI strategy brief.
 *
 * Anyone with the short URL `/brief/:slug` lands here. Renders the
 * brief markdown using the same ReactMarkdown styling as the in-app
 * report, plus a TopUni masthead, an SEO-friendly meta block, a
 * "Build yours" CTA, and a quiet "Made with TopUni AI" attribution.
 *
 * Each page view increments view_count via an RPC. Soft-deleted /
 * expired briefs return 404.
 */
import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowRight, ExternalLink, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import Navigation from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import { EnrichedMarkdown } from "@/components/EnrichedMarkdown";
import type { InlineScholarshipData } from "@/components/InlineScholarshipCard";

interface SharedBrief {
  brief_id: string;
  slug: string;
  content: string;
  language: "en" | "ru";
  report_grade: "basic" | "premium";
  profile_first_name: string | null;
  profile_grade_level: string | null;
  profile_major: string | null;
  profile_target_countries: string[] | null;
  created_at: string;
  view_count: number;
  is_public: boolean;
  expires_at: string | null;
}

const SharedBriefPage = () => {
  const { slug } = useParams<{ slug: string }>();
  const [brief, setBrief] = useState<SharedBrief | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);
  const [scholarshipsForCards, setScholarshipsForCards] = useState<InlineScholarshipData[]>([]);

  // Pull every name the brief wraps in **bold** so we can resolve them to
  // real scholarship rows. Names that don't exist in the DB just render as
  // bold text — EnrichedMarkdown handles that gracefully.
  const candidateNames = useMemo(() => {
    if (!brief?.content) return [] as string[];
    const set = new Set<string>();
    const re = /\*\*([^*\n]{6,80})\*\*/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(brief.content)) !== null) {
      const v = m[1].trim();
      // Filter out obvious non-scholarship bolds (sentences ending in punctuation, plain
      // labels like "Why it works for you:")
      if (v.endsWith(":") || v.endsWith(".")) continue;
      if (v.split(/\s+/).length < 1) continue;
      set.add(v);
    }
    return Array.from(set).slice(0, 30);
  }, [brief?.content]);

  // Resolve candidate names → real scholarship rows via ILIKE-any fuzzy match.
  // Runs once per brief load. RLS on scholarships allows anon select.
  useEffect(() => {
    if (candidateNames.length === 0) {
      setScholarshipsForCards([]);
      return;
    }
    let cancelled = false;
    (async () => {
      // Build OR clause: name.ilike.%X%,name.ilike.%Y%...
      const orClause = candidateNames
        .slice(0, 12)
        .map(n => `scholarship_name.ilike.%${n.replace(/[%,()]/g, "")}%`)
        .join(",");
      const { data } = await supabase
        .from("scholarships")
        .select("scholarship_id, scholarship_name, provider_name, host_country, coverage_type, award_amount_text, application_deadline, official_url")
        .or(orClause)
        .limit(40);
      if (cancelled || !data) return;
      setScholarshipsForCards(
        data.map(d => ({
          scholarship_id: d.scholarship_id,
          scholarship_name: d.scholarship_name,
          provider_name: d.provider_name,
          host_country: d.host_country,
          coverage_type: d.coverage_type,
          award_amount_text: d.award_amount_text,
          application_deadline: d.application_deadline,
          official_url: d.official_url,
        })),
      );
    })();
    return () => { cancelled = true; };
  }, [candidateNames]);

  useEffect(() => {
    if (!slug) {
      setNotFound(true);
      setLoading(false);
      return;
    }
    let cancelled = false;
    (async () => {
      const { data, error } = await supabase
        .from("shared_briefs")
        .select("*")
        .eq("slug", slug)
        .eq("is_public", true)
        .maybeSingle<SharedBrief>();

      if (cancelled) return;

      if (error || !data) {
        setNotFound(true);
        setLoading(false);
        return;
      }
      // Respect expiry — RLS already filters but be defensive
      if (data.expires_at && new Date(data.expires_at) < new Date()) {
        setNotFound(true);
        setLoading(false);
        return;
      }
      setBrief(data);
      setLoading(false);
      // Fire-and-forget view counter
      supabase.rpc("increment_brief_view", { p_slug: slug }).then(() => {});

      // Set page meta for SEO + social previews (Twitter / LinkedIn /
      // WhatsApp / iMessage / Slack all read these). The dynamic OG
      // image is generated by the og-brief edge function — content-
      // aware: shows the student's name, target countries, and major
      // baked into a TopUni-branded card.
      const firstName = data.profile_first_name || "A student";
      const major = data.profile_major ? ` ${data.profile_major}` : "";
      const target =
        data.profile_target_countries && data.profile_target_countries.length > 0
          ? ` for ${data.profile_target_countries.slice(0, 2).join(" & ")}`
          : "";
      const title = `${firstName}'s${major} admissions strategy${target} — TopUni`;
      const desc = (() => {
        // Use the FIRST paragraph of the brief content as the description
        // so social cards read like a real preview, not a generic blurb.
        const firstPara = (data.content || "")
          .replace(/^#+\s*.*$/gm, "")           // strip headings
          .replace(/\*\*([^*]+)\*\*/g, "$1")    // strip bold markers
          .split(/\n\n+/)
          .map((p) => p.trim())
          .find((p) => p.length > 40);
        if (firstPara) return firstPara.replace(/\s+/g, " ").slice(0, 220) + "…";
        return `An AI-generated university admissions strategy from TopUni Consulting${major}${target}.`;
      })();
      const url = `https://topuni.org/brief/${data.slug}`;
      const ogImage = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/og-brief?slug=${encodeURIComponent(data.slug)}`;
      const fallbackImage = "https://topuni.org/og-brief-fallback.png";

      document.title = title;

      const metaTags: { name?: string; property?: string; content: string }[] = [
        { name: "description", content: desc },
        // Open Graph (Facebook, LinkedIn, WhatsApp, iMessage, Slack)
        { property: "og:title",        content: title },
        { property: "og:description",  content: desc },
        { property: "og:type",         content: "article" },
        { property: "og:url",          content: url },
        { property: "og:site_name",    content: "TopUni Consulting" },
        { property: "og:image",        content: ogImage },
        { property: "og:image:width",  content: "1200" },
        { property: "og:image:height", content: "630" },
        { property: "og:image:alt",    content: title },
        { property: "article:published_time", content: data.created_at },
        // Twitter cards
        { name: "twitter:card",        content: "summary_large_image" },
        { name: "twitter:site",        content: "@topuniorg" },
        { name: "twitter:title",       content: title },
        { name: "twitter:description", content: desc },
        { name: "twitter:image",       content: ogImage },
      ];
      const _ = fallbackImage; // reserved for future graceful degradation

      for (const m of metaTags) {
        const sel = m.name ? `meta[name="${m.name}"]` : `meta[property="${m.property}"]`;
        let el = document.querySelector(sel);
        if (!el) {
          el = document.createElement("meta");
          if (m.name) el.setAttribute("name", m.name);
          if (m.property) el.setAttribute("property", m.property);
          document.head.appendChild(el);
        }
        el.setAttribute("content", m.content);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [slug]);

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Loader2 className="h-6 w-6 text-muted-foreground animate-spin" />
      </div>
    );
  }

  if (notFound || !brief) {
    return (
      <div className="min-h-screen bg-background">
        <Navigation />
        <div className="max-w-xl mx-auto px-6 pt-20 pb-32 text-center">
          <p className="text-[11px] uppercase tracking-[0.22em] text-gold-dark font-semibold mb-3">404</p>
          <h1 className="font-heading text-2xl font-bold text-foreground mb-3">This brief isn't available.</h1>
          <p className="text-sm text-muted-foreground leading-relaxed mb-8">
            Briefs from anonymous students expire after 30 days. The link may also have been revoked by its owner.
          </p>
          <Button variant="gold" asChild>
            <Link to="/topuni-ai">
              Build your own strategy <ArrowRight className="ml-2 w-4 h-4" />
            </Link>
          </Button>
        </div>
        <Footer language="en" />
      </div>
    );
  }

  const firstName = brief.profile_first_name?.trim();
  const targetCountries = brief.profile_target_countries || [];
  const major = brief.profile_major;
  const isRu = brief.language === "ru";

  return (
    <div className="min-h-screen bg-background">
      <Navigation />

      {/* Hero / masthead — signals "this is a real brief from TopUni AI" */}
      <section className="bg-gradient-to-br from-primary via-primary to-primary/95 py-14 sm:py-20">
        <div className="max-w-3xl mx-auto px-5 sm:px-8">
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <p className="text-[11px] uppercase tracking-[0.22em] text-gold font-semibold mb-3">
              {isRu ? "Стратегический брифинг" : "Strategic Brief"}
            </p>
            <h1 className="font-heading text-3xl sm:text-4xl md:text-5xl font-bold text-primary-foreground tracking-tight leading-tight">
              {firstName
                ? `${firstName}'s admissions strategy`
                : isRu
                  ? "Стратегия поступления"
                  : "An admissions strategy"}
            </h1>
            <div className="mt-5 flex flex-wrap gap-2">
              {targetCountries.slice(0, 5).map((c) => (
                <span
                  key={c}
                  className="text-[11px] uppercase tracking-[0.18em] font-semibold text-primary-foreground/85 border border-primary-foreground/25 px-2.5 py-1 rounded-full"
                >
                  {c}
                </span>
              ))}
              {major && (
                <span className="text-[11px] uppercase tracking-[0.18em] font-semibold text-gold border border-gold/40 px-2.5 py-1 rounded-full">
                  {major}
                </span>
              )}
            </div>
          </motion.div>
        </div>
      </section>

      {/* Brief content */}
      <article className="max-w-3xl mx-auto px-5 sm:px-8 py-14 sm:py-20">
        <div
          className="prose prose-sm sm:prose-base max-w-none
                     [&_h2]:text-foreground [&_h2]:font-heading [&_h2]:text-2xl [&_h2]:mt-10 [&_h2]:mb-4 [&_h2]:tracking-tight
                     [&_h3]:text-foreground [&_h3]:font-heading [&_h3]:text-lg [&_h3]:mt-8 [&_h3]:mb-3
                     [&_p]:text-foreground/90 [&_p]:leading-relaxed
                     [&_li]:text-foreground/90 [&_li]:leading-relaxed
                     [&_strong]:text-foreground"
        >
          <EnrichedMarkdown scholarships={scholarshipsForCards}>
            {brief.content}
          </EnrichedMarkdown>
        </div>

        {/* Branding + CTA */}
        <div className="not-prose mt-16 pt-8 border-t border-border">
          <div className="bg-card border border-border rounded-2xl p-7 sm:p-9 text-center">
            <p className="text-[11px] uppercase tracking-[0.22em] text-gold-dark font-semibold mb-3">
              {isRu ? "Сделано с TopUni AI" : "Made with TopUni AI"}
            </p>
            <h3 className="font-heading text-2xl font-bold tracking-tight text-foreground mb-3 leading-tight">
              {isRu ? "Хочешь свой такой?" : "Want one of your own?"}
            </h3>
            <p className="text-sm text-muted-foreground leading-relaxed max-w-md mx-auto mb-6">
              {isRu
                ? "Заполни короткую анкету, и TopUni AI соберёт стратегию: позиционирование, шорт-лист университетов, стипендии и план на 90 дней."
                : "Fill out a short profile and TopUni AI will draft your own strategy — positioning, university shortlist, scholarship pathway, and 90-day action plan."}
            </p>
            <Button variant="gold" size="lg" asChild>
              <Link to={isRu ? "/topuni-ai/ru" : "/topuni-ai"} className="gap-2">
                {isRu ? "Создать мой брифинг" : "Build my strategic brief"}
                <ArrowRight className="w-4 h-4" />
              </Link>
            </Button>
            <p className="text-[11px] text-muted-foreground/70 mt-4">
              {isRu ? "Бесплатно. 60 секунд." : "Free. 60 seconds."}
            </p>
          </div>

          <p className="text-[10px] text-muted-foreground/60 text-center mt-6">
            {isRu ? "Сгенерировано" : "Generated"}{" "}
            {new Date(brief.created_at).toLocaleDateString(isRu ? "ru-RU" : "en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
            })}
            {brief.view_count > 1 && ` · ${brief.view_count} ${isRu ? "просмотров" : "views"}`}
          </p>
        </div>
      </article>

      <Footer language={isRu ? "ru" : "en"} />
    </div>
  );
};

export default SharedBriefPage;
