/// <reference types="npm:@types/react@18.3.1" />
import * as React from 'npm:react@18.3.1'
import {
  Body, Container, Head, Heading, Hr, Html, Preview, Section, Text,
} from 'npm:@react-email/components@0.0.22'
import type { TemplateEntry } from './registry.ts'

// member-kpi-digest — fired daily by daily-kpi-digest-cron to the
// founder team. Yesterday's numbers in one minute: signups, MRR delta,
// churn, wizard-to-signup conversion, deltas vs prior 7-day average.

interface Props {
  forDateLabel: string
  signups24h: number
  payingMembers: number
  mrrUsd: number
  mrrDelta24hUsd: number
  churned24h: number
  wizardCompletions24h: number
  wizardToSignupRate?: number
  topNote?: string
  language?: 'en' | 'ru'
}

const KpiDigest: React.FC<Props> = (p) => (
  <Html>
    <Head />
    <Preview>{`TopUni · ${p.signups24h} signup(s) · $${p.mrrUsd.toFixed(0)} MRR`}</Preview>
    <Body style={{ backgroundColor: '#f6f5f1', fontFamily: 'Georgia, serif', color: '#1a1a1a' }}>
      <Container style={{ maxWidth: 560, margin: '24px auto', padding: 24, backgroundColor: '#ffffff', borderRadius: 8 }}>
        <Text style={{ fontSize: 12, letterSpacing: '0.08em', textTransform: 'uppercase', color: '#8a7a3f', margin: 0 }}>
          TopUni · Daily KPIs · {p.forDateLabel}
        </Text>
        <Heading as="h1" style={{ fontSize: 22, margin: '8px 0 16px', color: '#0a2540' }}>
          Yesterday in 6 numbers
        </Heading>
        <Hr style={{ borderColor: '#e4e1d6', margin: '0 0 16px' }} />
        <Section>
          <Text style={{ margin: '6px 0' }}><strong>Signups (24h):</strong> {p.signups24h}</Text>
          <Text style={{ margin: '6px 0' }}><strong>Paying members:</strong> {p.payingMembers}</Text>
          <Text style={{ margin: '6px 0' }}>
            <strong>MRR:</strong> ${p.mrrUsd.toFixed(2)}{' '}
            {p.mrrDelta24hUsd !== 0 && (
              <span style={{ color: p.mrrDelta24hUsd > 0 ? '#0a6d2c' : '#992525' }}>
                ({p.mrrDelta24hUsd > 0 ? '+' : ''}${p.mrrDelta24hUsd.toFixed(2)} vs prior day)
              </span>
            )}
          </Text>
          <Text style={{ margin: '6px 0' }}><strong>Churn (24h):</strong> {p.churned24h}</Text>
          <Text style={{ margin: '6px 0' }}><strong>Wizard completions (24h):</strong> {p.wizardCompletions24h}</Text>
          {typeof p.wizardToSignupRate === 'number' && (
            <Text style={{ margin: '6px 0' }}>
              <strong>Wizard → signup:</strong> {(p.wizardToSignupRate * 100).toFixed(1)}%
            </Text>
          )}
        </Section>
        {p.topNote && (
          <>
            <Hr style={{ borderColor: '#e4e1d6', margin: '16px 0' }} />
            <Text style={{ fontSize: 13, color: '#444', margin: 0 }}>{p.topNote}</Text>
          </>
        )}
        <Hr style={{ borderColor: '#e4e1d6', margin: '24px 0 12px' }} />
        <Text style={{ fontSize: 12, color: '#666', margin: 0 }}>
          Generated by daily-kpi-digest-cron. /admin/analytics for the full breakdown.
        </Text>
      </Container>
    </Body>
  </Html>
)

export const template: TemplateEntry = {
  component: KpiDigest,
  subject: (data) => {
    const n = (data.signups24h as number) ?? 0
    const mrr = (data.mrrUsd as number) ?? 0
    return `TopUni · ${n} signup${n === 1 ? '' : 's'} yesterday · $${mrr.toFixed(0)} MRR`
  },
  to: 'samuel.shn.han@gmail.com',
  displayName: 'Daily KPI digest',
  previewData: {
    forDateLabel: '2026-05-28',
    signups24h: 2,
    payingMembers: 7,
    mrrUsd: 279.93,
    mrrDelta24hUsd: 79.98,
    churned24h: 0,
    wizardCompletions24h: 18,
    wizardToSignupRate: 0.11,
    topNote: 'Two signups via the Pricing page. No churn. Conversion holding.',
  },
}
