-- =============================================================================
-- match_scholarships — trust calibration via confidence + completeness
-- =============================================================================
-- SUPERSEDED IN-FLIGHT BY 20260507240000.
--
-- The original body created a 6-arg overload of public.match_scholarships
-- that called the legacy 5-arg public.scholarship_passes_eligibility.
-- After 20260505040000 added a 7-arg variant of that predicate (with
-- TOEFL+SAT defaults), the 5-arg call became ambiguous (`function ... is
-- not unique`, SQLSTATE 42725). Migration 20260507240000 ships the
-- canonical 8-arg match_scholarships with trust calibration applied AND
-- drops the 6-arg ghost — superseding this file entirely.
--
-- The required `confidence` column on public.scholarships is added at
-- the top of 20260507220000 (next file in the chain) so the same
-- transaction defines the column AND the breakdown function that
-- references it.
--
-- This file is recorded as a no-op so the migration ledger stays clean.
-- =============================================================================

DO $$ BEGIN PERFORM 1; END $$;
