
INSERT INTO public.scholarships (
  scholarship_name, provider_name, host_country, official_url,
  coverage_type, award_amount_text, estimated_total_value_usd, duration_text, renewable, award_type,
  target_degree_level, target_fields,
  min_gpa, gpa_scale, min_ielts, min_toefl, min_sat,
  language_requirements, citizenship_requirements, eligible_countries, age_limit,
  financial_need_required, leadership_required, extracurricular_required,
  deadline_type, essay_required, recommendation_letters_required, interview_required,
  separate_application_required, application_fee_text, application_platform,
  selectivity_level, effort_level, effort_reason,
  ideal_candidate_profile, weak_candidate_warning,
  best_for_tags, why_this_fits, how_to_win, what_to_prepare_first, next_step, risk_note,
  eligibility_requirements, verified, last_verified_date
) VALUES
('US Need-Blind Consortium (Harvard, Yale, MIT, Princeton, Amherst, Bowdoin, Brown, Dartmouth, Notre Dame)', 'Multiple US Universities', 'United States', 'https://www.harvard.edu/financial-aid',
 'full_ride', 'Up to $91,312/year (full cost of attendance, no loans)', 365000, '4 years', true, ARRAY['merit','need_based'],
 ARRAY['undergraduate'], ARRAY['any'],
 NULL, 4.0, 7.0, 100, 1500,
 'TOEFL 100+ / IELTS 7.0+ typical; SAT 1500+ / ACT 33+ competitive', 'Open to all nationalities including undocumented students', ARRAY['any'], 'No age limit',
 true, true, true,
 'annual', true, 2, true, true, '$75-$85 (waivers available)', 'Common App / Coalition / direct',
 'Highly Selective','High','Need-blind admission means financial situation does not affect decision; full need is met without loans for admitted internationals.',
 'Top of cohort academically with sustained leadership, intellectual depth, and a coherent narrative. Test scores, essays, and rigor of curriculum all matter.',
 'Without strong testing, top-decile grades, and clear extracurricular impact, the international applicant pool is brutal - 3-7% admit rates.',
 ARRAY['undergrad','need_based','elite_us','no_loans'],
 'Only US route that ignores ability to pay for international applicants.',
 'Distinctive narrative + top academics + concrete impact, not generic leadership.',
 'Strong SAT/ACT, polished personal essay, two teacher recommendations, counselor letter.',
 'Pick 2-3 need-blind targets and start essays 6 months before deadline.',
 'Need is met but admission rates are 3-7% - pair with safer financial-aid schools.',
 'Top US universities meeting 100% of demonstrated need for international students with no loans. Need-blind admissions.', true, '2026-04-26'),

('Knight-Hennessy Scholars', 'Stanford University', 'United States', 'https://knight-hennessy.stanford.edu/',
 'full_ride', 'Full tuition + living stipend (~$120k over 3 years)', 350000, 'Up to 3 years', false, ARRAY['merit','leadership'],
 ARRAY['masters','phd'], ARRAY['any'],
 3.7, 4.0, 7.0, 100, NULL,
 'TOEFL/IELTS per Stanford department; GRE/GMAT per program', 'Open to all nationalities', ARRAY['any'], 'No age limit',
 false, true, true,
 'annual', true, 3, true, true, '$125', 'Knight-Hennessy portal + Stanford grad app',
 'Highly Selective','High','Requires admission to a Stanford graduate program AND a separate Knight-Hennessy application with extensive essays and references.',
 'Demonstrated leadership at scale, civic mindset, and proof of independent thinking. Stanford-grade academics expected.',
 'Generic profiles and weak Stanford program fit are filtered out fast - 100 scholars from 7,000+ applicants.',
 ARRAY['grad','leadership','full_ride','interdisciplinary'],
 'Most generous fully funded grad program in the world; pairs funding with a leadership cohort.',
 'Lead with one specific systems-level problem you have already moved on, not a portfolio of titles.',
 'Stanford program shortlist, GRE/GMAT if needed, two recommenders who can speak to leadership.',
 'Identify Stanford department fit, then start essays 4+ months early.',
 'Must also be admitted to a Stanford graduate program - two acceptances required.',
 'Full funding for any Stanford grad program plus leadership development cohort.', true, '2026-04-26'),

('Fulbright Foreign Student Program', 'US Department of State', 'United States', 'https://foreign.fulbrightonline.org/apply',
 'full_ride', 'Full tuition + stipend + health + travel (varies by country)', 80000, '1-2 years', false, ARRAY['merit','government'],
 ARRAY['masters','phd','research'], ARRAY['any'],
 NULL, 4.0, 6.5, 79, NULL,
 'TOEFL iBT 79 / PBT 550 / IELTS 6.5 minimum', '~160 countries; dual US citizens excluded', ARRAY['any'], 'No age limit',
 false, true, true,
 'annual', true, 3, true, true, 'Free', 'Country-specific Fulbright Commission',
 'Highly Selective','High','Country-specific quotas, multi-stage interview, and J-1 visa with 2-year home-residency requirement.',
 'Mid-career or recent graduate with clear research/study plan that ties back to home-country development.',
 'Vague study objectives and weak ties to home-country impact are the most common rejection reasons.',
 ARRAY['grad','government','j1_visa','home_return'],
 'Government-backed, prestigious, opens US grad doors with strong post-study network.',
 'Specific, narrow study objective tied to a measurable home-country problem.',
 'TOEFL/IELTS, study objective essay, personal statement, three recommenders.',
 'Contact your country Fulbright Commission 12+ months before deadline.',
 '2-year home-return mandate (J-1) limits direct US employment after study.',
 'Fulbright Foreign Student offers fully funded US graduate study with mandatory home return.', true, '2026-04-26'),

('Chevening Scholarships', 'UK Foreign Commonwealth and Development Office', 'United Kingdom', 'https://www.chevening.org/',
 'full_ride', 'Full tuition + monthly stipend + travel + visa', 55000, '1 year', false, ARRAY['merit','government','leadership'],
 ARRAY['masters'], ARRAY['any'],
 NULL, 4.0, 6.5, 79, NULL,
 'Meets UK university English requirement (typically IELTS 6.5)', 'Citizens of Chevening-eligible countries (Global South, Central Asia, etc.)', ARRAY['any'], 'No age limit',
 false, true, true,
 'annual', true, 2, true, true, 'Free', 'Chevening online application',
 'Highly Selective','High','Requires 2,800 hours (~2 years) work experience, 3 UK course offers, 4 essays, and 2-year home return.',
 'Emerging leader with 2+ years experience, clear career plan, and demonstrated influence.',
 'Without 2+ years work experience and 3 UK university offers in hand, application is incomplete.',
 ARRAY['grad','leadership','uk','government'],
 'UK flagship scholarship; explicit mandate to fund future leaders from Central Asia and Global South.',
 'Sharp leadership essay with concrete examples; fit-for-UK essay tied to bilateral priorities.',
 'CV showing 2,800 work hours, 3 UK university offers, 2 references.',
 'Apply for UK university offers in parallel with Chevening (Aug-Nov window).',
 '2-year home-return requirement enforced.',
 'UK government masters scholarship for emerging leaders with 2+ years work experience.', true, '2026-04-26'),

('Gates Cambridge Scholarships', 'Gates Cambridge Trust', 'United Kingdom', 'https://www.gatescambridge.org/',
 'full_ride', 'Full tuition + GBP 22,050 maintenance + travel + family/child support', 90000, '1-4 years', false, ARRAY['merit','leadership'],
 ARRAY['masters','phd'], ARRAY['any'],
 NULL, 4.0, 7.5, 100, NULL,
 'Meets Cambridge entry requirements (typically IELTS 7.5 / TOEFL 110)', 'All non-UK citizens', ARRAY['any'], 'No age limit',
 false, true, true,
 'annual', true, 3, true, true, 'GBP 75 Cambridge fee', 'Cambridge graduate application + Gates section',
 'Highly Selective','High','Must be admitted to Cambridge AND selected by Gates committee. ~80 scholars per year from thousands.',
 'Outstanding academic record + commitment to improving the lives of others, with capacity for leadership.',
 'No explicit GPA floor but typical scholars are first-class equivalents at top global institutions.',
 ARRAY['grad','phd','leadership','full_ride'],
 'Most generous Cambridge funding; covers family expenses unlike most scholarships.',
 'Show measurable commitment to social impact, not just academic excellence.',
 'Cambridge program fit, research proposal (PhD), personal Gates statement.',
 'Submit Cambridge application by the early Gates deadline (typically Dec 3 or Jan 5).',
 'Two-stage selection - Cambridge offer first, then Gates shortlist.',
 'Full funding for any Cambridge graduate program plus family allowances.', true, '2026-04-26'),

('Rhodes Scholarships', 'Rhodes Trust', 'United Kingdom', 'https://www.rhodeshouse.ox.ac.uk/',
 'full_ride', 'Full Oxford tuition + ~GBP 18,000 living stipend', 100000, '2 years (extendable to 3)', true, ARRAY['merit','leadership'],
 ARRAY['masters','phd'], ARRAY['any'],
 3.7, 4.0, 7.5, 110, NULL,
 'Oxford entry requirements (typically IELTS 7.5 / TOEFL 110)', 'Specific global constituencies + global pool', ARRAY['any'], '18-24 at application',
 false, true, true,
 'annual', true, 6, true, true, 'Free', 'Rhodes constituency portal',
 'Highly Selective','High','Constituency-based selection (e.g., 2 per year for some countries) with intense interview rounds. ~100 scholars globally.',
 'Top academic record, demonstrated leadership, energy to lead and serve, with physical/moral character.',
 'Age ceiling (24 at Oct 1 of entry year) is hard. Strong service record required.',
 ARRAY['grad','leadership','oxford','prestigious'],
 'The original international scholarship; strongest global alumni network in academia and policy.',
 'Distinct, specific story of service combined with academic excellence - not a list of clubs.',
 '6 reference letters, personal statement, transcript, Oxford program shortlist.',
 'Check your constituency deadline (varies; many July-Aug).',
 'Tight age limit (24) excludes many mid-career applicants.',
 'Oxford scholarship for outstanding young leaders aged 18-24 with strong academics.', true, '2026-04-26'),

('Erasmus Mundus Joint Masters', 'European Commission', 'European Union', 'https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters',
 'full_ride', 'Full tuition + EUR 1,400/month + travel + insurance', 60000, '1-2 years', false, ARRAY['merit'],
 ARRAY['masters'], ARRAY['any'],
 NULL, 4.0, 6.5, 90, NULL,
 'IELTS 6.5+ / TOEFL 90+ (consortium-specific)', 'Open to all nationalities (Partner Country quotas favored)', ARRAY['any'], 'No age limit',
 false, false, false,
 'annual', true, 2, false, true, 'Free', 'Each EMJM consortium portal',
 'Highly Selective','High','Apply directly to specific consortia (Dec-Feb deadlines). Mobility across 2+ EU countries mandatory.',
 'Academic specialist seeking interdisciplinary masters with a strong research or industry orientation.',
 'Confused or undifferentiated program fit is the top rejection reason.',
 ARRAY['grad','eu','interdisciplinary','mobility'],
 'Studies in 2-4 EU countries with one funded scholarship; strong for niche interdisciplinary masters.',
 'Pick 2-3 consortia where your background is genuinely a fit, not 6 applications.',
 'CV, motivation letter per consortium, recommendations, transcripts.',
 'Browse the EMJM catalog and shortlist consortia by November.',
 'Mandatory mobility (move countries 2-4 times in 1-2 years).',
 'EU-funded joint masters with mobility across multiple universities.', true, '2026-04-26'),

('Eiffel Excellence Scholarship', 'French Ministry for Europe and Foreign Affairs', 'France', 'https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence',
 'partial', 'EUR 1,181/month for masters; EUR 1,700/month for PhD + travel + insurance', 25000, '1-2 years (Masters); up to 12 months (PhD)', false, ARRAY['merit','government'],
 ARRAY['masters','phd'], ARRAY['engineering','science','economics','law','political_science'],
 NULL, 4.0, NULL, NULL, NULL,
 'French C1 or English equivalent (course-dependent)', 'Non-French citizens', ARRAY['any'], 'Under 29 (Masters); under 33 (PhD)',
 false, false, false,
 'annual', true, 2, false, false, 'Free', 'Nominated by French institution only',
 'Highly Selective','Medium','Cannot self-apply - must be nominated by a French institution. Tuition not covered (only stipend).',
 'Strong masters or PhD candidate already in dialogue with a French school.',
 'No nomination = no application. Must secure French institution sponsorship first.',
 ARRAY['grad','france','europe','stipend'],
 'Stipend-focused; pair with low French tuition fees for an affordable European masters.',
 'Land the institutional nomination - that is 80% of the work.',
 'French institution shortlist + faculty contact 6+ months before nomination deadline.',
 'Email program coordinators at target French schools by September.',
 'Tuition not covered (most public French masters are <EUR 5,000/year for non-EU).',
 'French government stipend for top masters/PhD candidates - institutional nomination required.', true, '2026-04-26'),

('Swedish Institute Scholarships for Global Professionals (SISGP)', 'Swedish Institute', 'Sweden', 'https://si.se/en/apply/scholarships/',
 'full_ride', 'Full tuition + SEK 12,000/month + SEK 15,000 travel + insurance', 45000, '1-2 years', false, ARRAY['merit','leadership'],
 ARRAY['masters'], ARRAY['any'],
 NULL, 4.0, 6.5, 90, NULL,
 'English proficiency per Swedish university admission', '~40 specific countries (incl. Armenia, Azerbaijan, Uzbekistan, Bangladesh)', ARRAY['Armenia','Azerbaijan','Uzbekistan','Bangladesh','Ethiopia','Indonesia','Kenya'], 'No age limit',
 false, true, true,
 'annual', true, 2, false, true, 'SEK 900 university fee', 'Swedish university admission + SI portal',
 'Highly Selective','High','Must apply to Swedish universities first (Jan deadline), then SI scholarship (Feb deadline). 3,000 hours work experience required.',
 'Mid-career professional with leadership track record from an eligible developing country.',
 'No work experience or weak leadership story = automatic filter.',
 ARRAY['grad','sweden','leadership','developing'],
 'Sweden offers world-class engineering and sustainability masters with strong English-medium programs.',
 'Lead the leadership essay with one specific case where you mobilized others.',
 'Swedish university applications by Jan 15; SI scholarship by Feb.',
 'Apply to Swedish universities first via universityadmissions.se.',
 'Excludes dual EU citizens; eligibility list is strict.',
 'SI fully funds masters in Sweden for mid-career leaders from eligible developing nations.', true, '2026-04-26'),

('Stipendium Hungaricum', 'Tempus Public Foundation', 'Hungary', 'https://stipendiumhungaricum.hu/',
 'full_ride', 'Full tuition + monthly stipend + accommodation + medical', 18000, '2-6 years', true, ARRAY['government'],
 ARRAY['undergraduate','masters','phd'], ARRAY['any'],
 NULL, 4.0, NULL, NULL, NULL,
 'Per institution; English or Hungarian tracks', '~80 partner nations including Central Asian states', ARRAY['Kazakhstan','Kyrgyzstan','Uzbekistan','Tajikistan','Azerbaijan','Armenia'], 'No age limit',
 false, false, false,
 'annual', true, 2, true, true, 'Free', 'apply.stipendiumhungaricum.hu',
 'Selective','Medium','Must be nominated by sending partner (e.g., national education ministry). Min 56/100 on entrance exam.',
 'Cost-conscious applicant from a partner country looking for affordable EU degree.',
 'Without home-country nomination from the sending partner, the application is invalid.',
 ARRAY['undergrad','grad','eu','partner_nominated'],
 'Most accessible fully-funded EU pathway for Central Asian students.',
 'Get the home-country nomination first - it is the gatekeeper.',
 'Home-country sending partner contact, transcripts, motivation letter.',
 'Contact your country education ministry by October.',
 'Mandatory Hungarian culture class; some programs require Hungarian language.',
 'Hungarian government scholarship covering UG/Masters/PhD for partner-country citizens.', true, '2026-04-26'),

('Schwarzman Scholars', 'Schwarzman College, Tsinghua University', 'China', 'https://www.schwarzmanscholars.org/',
 'full_ride', 'Full tuition + room + board + $4,000 personal stipend + travel', 75000, '1 year', false, ARRAY['merit','leadership'],
 ARRAY['masters'], ARRAY['public_policy','business','international_studies'],
 NULL, 4.0, 7.0, 100, NULL,
 'High English proficiency (no GRE/GMAT required)', 'Open to all nationalities (40% US / 20% China / 40% rest of world)', ARRAY['any'], '18-28 at enrollment',
 false, true, true,
 'annual', true, 3, true, true, 'Free', 'app.schwarzmanscholars.org',
 'Highly Selective','High','Holistic review with no GPA floor; intense semi-finalist interviews. ~150 scholars from 4,000+ applicants.',
 'Future global leader with measurable impact and curiosity about China role in the world.',
 'Pure academic profile without leadership impact rarely advances past first round.',
 ARRAY['grad','china','leadership','full_ride'],
 'Designed to build US-China-World leader cohort; strong post-program network.',
 'Specific story of leading something hard, plus curiosity about China - not just admiration.',
 'CV, 3 essays, 3 recommenders, video statement.',
 'Start essays in June for September deadline.',
 'Hard age cap of 28 at enrollment.',
 'Tsinghua-based 1-year masters in Global Affairs; cohort-driven leadership program.', true, '2026-04-26'),

('Chinese Government Scholarship (CSC)', 'China Scholarship Council', 'China', 'https://www.campuschina.org/',
 'full_ride', 'Full tuition + monthly stipend (CNY 2,500-3,500) + accommodation + medical', 15000, '4 years (UG) / 2-3 years (Masters) / 3-4 years (PhD)', true, ARRAY['government'],
 ARRAY['undergraduate','masters','phd'], ARRAY['any'],
 2.5, 4.0, 6.5, 80, NULL,
 'HSK 3/4 for Chinese-taught; IELTS 6.5 / TOEFL 80 for English-taught', 'Non-Chinese citizens', ARRAY['any'], 'BA <25; MA <35; PhD <40',
 false, false, false,
 'annual', true, 2, false, true, 'Free', 'Embassy / university / CSC portal (Type A/B/C)',
 'Selective','Medium','Three application channels (Type A embassy, Type B university, Type C provincial). Travel costs not covered.',
 'Cost-conscious student wanting a degree at a top Chinese university.',
 'GPA below 2.5/4.0 typically filtered out.',
 ARRAY['undergrad','grad','china','full_ride'],
 'Lowest-friction full-ride into a top-100 university for many Central Asian students.',
 'Apply via Type A (embassy) for highest selectivity, Type B (university) for best academic fit.',
 'HSK or IELTS, 2 recommenders, study plan, foreigner physical exam form.',
 'Contact the Chinese embassy in your country by January.',
 'Travel costs and visa fees not covered.',
 'CSC fully funds UG/Masters/PhD at Chinese universities for non-Chinese citizens.', true, '2026-04-26'),

('Global Korea Scholarship (GKS)', 'NIIED, Korean Ministry of Education', 'South Korea', 'https://www.studyinkorea.go.kr/',
 'full_ride', 'Full tuition + KRW 1,000,000/month + Korean language year + airfare + insurance', 25000, '2-3 years (Masters) / 3-4 years (PhD)', true, ARRAY['government'],
 ARRAY['masters','phd'], ARRAY['any'],
 2.64, 4.0, NULL, NULL, NULL,
 'TOPIK preferred; English proficiency for English-medium programs', 'Non-Korean citizens; +5% for descendants of Korean War veterans', ARRAY['any'], 'Under 40',
 false, false, false,
 'annual', true, 2, false, true, 'Free', 'Embassy or university channel',
 'Selective','Medium','Min 80% percentile or 2.64/4.0 GPA. Embassy track typically more competitive than university track.',
 'Strong masters/PhD candidate interested in Korea-relevant research or industry.',
 'GPA below 2.64/4.0 or 80th percentile is automatic disqualification.',
 ARRAY['grad','korea','government','full_ride'],
 'Includes a year of Korean language training + integration into Korean grad ecosystem.',
 'Apply via embassy track if your country has few applicants - better odds.',
 'Transcripts, study plan, 2 recommenders, self-introduction.',
 'Contact your local Korean embassy by February.',
 'TOPIK strongly preferred even for English-medium programs.',
 'Korean government masters/PhD scholarship with Korean language year included.', true, '2026-04-26'),

('Turkiye Burslari', 'Republic of Turkiye Presidency for Turks Abroad', 'Turkiye', 'https://turkiyeburslari.gov.tr/',
 'full_ride', 'Full tuition + monthly stipend + accommodation + airfare + insurance + Turkish year', 12000, '4 years (UG) / 2 years (Masters) / 4 years (PhD)', true, ARRAY['government'],
 ARRAY['undergraduate','masters','phd'], ARRAY['any'],
 NULL, 4.0, NULL, NULL, NULL,
 '1-year Turkish prep mandatory; English exams accepted for some programs', 'Non-Turkish citizens; priority for Central Asia, Africa, Global South', ARRAY['Kazakhstan','Kyrgyzstan','Uzbekistan','Tajikistan','Turkmenistan','Azerbaijan'], 'BA <21; MA <30; PhD <35',
 false, false, false,
 'annual', true, 2, true, true, 'Free', 'tbbs.turkiyeburslari.gov.tr',
 'Selective','Medium','BA >70%; MA >75%; Medicine/Dentistry >90%. Mandatory Turkish prep year.',
 'Central Asian or Global South applicant seeking affordable degree with Turkish language acquisition.',
 'Strict age caps; medical fields need 90% academic average.',
 ARRAY['undergrad','grad','turkey','central_asia_priority'],
 'Strong explicit priority for Central Asian and Turkic-speaking applicants.',
 'Use the priority status - emphasize regional and cultural ties.',
 'Transcripts, motivation letter, 2 recommenders, passport.',
 'Apply via tbbs portal (Jan-Feb window).',
 'Mandatory Turkish prep year delays start of degree by 12 months.',
 'Turkiye Burslari fully funds UG/Masters/PhD with priority for Central Asia and Global South.', true, '2026-04-26'),

('Asian Development Bank-Japan Scholarship (ADB-JSP)', 'Asian Development Bank', 'Multiple (Japan, Australia, NZ, etc.)', 'https://www.adb.org/work-with-us/careers/japan-scholarship-program',
 'full_ride', 'Full tuition + JPY 147,000/month (Japan) + travel + insurance', 35000, '1-2 years', false, ARRAY['government','development'],
 ARRAY['masters'], ARRAY['economics','public_policy','business','science','technology'],
 NULL, 4.0, 6.5, 79, NULL,
 'English proficiency per host institution', '38 ADB developing member countries', ARRAY['Kazakhstan','Kyrgyzstan','Uzbekistan','Tajikistan','Mongolia','Bangladesh','Pakistan'], 'Under 35',
 true, false, false,
 'annual', true, 2, false, true, 'Free', 'Apply through partner institution',
 'Selective','Medium','Must apply to and be admitted by an ADB-JSP partner institution first. Min 2 years full-time work experience. Income preference <$25k/year.',
 'Public-sector or development-focused professional from an ADB member country.',
 'No work experience or income above middle-class thresholds typically filtered out.',
 ARRAY['grad','development','asia','home_return'],
 'Built for development professionals; partner schools include University of Tokyo, KDI School, NUS, IIT.',
 'Pick a partner institution and program tightly aligned with your home-country development sector.',
 'University application + ADB-JSP form + 2 recommenders.',
 'Identify partner institution from ADB list and apply by their internal deadline.',
 '2-year mandatory home return.',
 'ADB scholarship for mid-career professionals from member developing countries.', true, '2026-04-26'),

('Joint Japan/World Bank Graduate Scholarship (JJ/WBGSP)', 'World Bank Group', 'Multiple (preferred partner universities)', 'https://www.worldbank.org/en/programs/scholarships',
 'full_ride', 'Full tuition + monthly stipend + travel + insurance', 60000, '1-2 years', false, ARRAY['government','development'],
 ARRAY['masters'], ARRAY['economics','public_policy','development','health'],
 NULL, 4.0, 6.5, 79, NULL,
 'English proficiency per host institution', '78 World Bank developing member countries; developed-nation citizens excluded', ARRAY['Kazakhstan','Kyrgyzstan','Uzbekistan','Tajikistan','Mongolia','Bangladesh'], 'Under 45',
 false, false, false,
 'annual', true, 2, false, true, 'Free', 'jjwbgsp portal',
 'Highly Selective','High','Min 3 years recent development-related work experience. Must be admitted to a JJ/WBGSP preferred program.',
 'Mid-career development professional with 3+ years on government, NGO, or international body work.',
 'Less than 3 years of development-relevant work or no preferred-program offer = ineligible.',
 ARRAY['grad','development','world_bank','home_return'],
 'Strongest signal for World Bank / IMF / multilateral career trajectory.',
 'Frame your work experience as direct development impact, not generic corporate work.',
 'Preferred-program offer letter, 2 recommenders, employment certificates.',
 'Check JJ/WBGSP preferred program list and apply by their deadlines.',
 '2-year home-return required; dual citizens of developed nations excluded.',
 'World Bank fully funds masters for mid-career development professionals.', true, '2026-04-26'),

('Mastercard Foundation Scholars Program', 'Mastercard Foundation', 'Multiple (US, Canada, Africa, Europe)', 'https://mastercardfdn.org/all/scholars/',
 'full_ride', 'Full tuition + living + travel + leadership development', 70000, '2-4 years', true, ARRAY['leadership','development'],
 ARRAY['undergraduate','masters'], ARRAY['climate','agriculture','public_policy','engineering'],
 NULL, 4.0, 6.5, 80, NULL,
 'English proficiency per partner institution', 'African citizens, refugees, displaced persons (with some Asian partner expansion)', ARRAY['Ghana','Rwanda','Kenya','Uganda','Ethiopia','Nigeria','South Africa'], 'Under 35',
 true, true, true,
 'annual', true, 2, true, true, 'Free', 'Per partner institution',
 'Highly Selective','High','Cohort-specific limits per partner. Demonstrated commitment to giving back to home community required.',
 'Academically strong African student with documented leadership and financial need.',
 'Profiles without clear give-back orientation are filtered out.',
 ARRAY['undergrad','grad','africa','leadership'],
 'Largest fully-funded program for African students globally.',
 'Show specific give-back plan, not generic intent to help.',
 'Partner-institution application + Mastercard supplementary essays.',
 'Pick partner institution from foundation list and apply by their deadline.',
 'Strict give-back expectation post-graduation.',
 'Mastercard Foundation funds African students at top global universities with leadership focus.', true, '2026-04-26'),

('Aga Khan Foundation International Scholarship Programme (ISP)', 'Aga Khan Foundation', 'Multiple (worldwide)', 'https://www.akdn.org/our-agencies/aga-khan-foundation/international-scholarship-programme',
 'partial', '50% grant / 50% interest-free loan covering tuition + living', 30000, '1-2 years', false, ARRAY['development','need_based'],
 ARRAY['masters','phd'], ARRAY['any'],
 NULL, 4.0, 6.5, 79, NULL,
 'English proficiency per host institution', 'Bangladesh, India, Pakistan, Afghanistan, Tajikistan, Kyrgyzstan, Syria, Egypt, Kenya, Tanzania, Uganda, Madagascar, Mozambique (specific eligibility)', ARRAY['Kyrgyzstan','Tajikistan','Afghanistan','Bangladesh','Pakistan','India'], 'Under 30 preferred',
 true, false, false,
 'annual', true, 2, true, true, 'Free', 'AKF country office',
 'Selective','Medium','50/50 grant-loan structure means recipients repay half over 5 years post-study. Country-eligibility list is strict.',
 'Need-based candidate from eligible developing country with strong academic and admissions record.',
 'Cannot fully cover need alone - applicants must show ability to cover gap.',
 ARRAY['grad','need_based','central_asia','partial'],
 'Rare partial-funding option specifically for Tajikistan, Kyrgyzstan, Afghanistan applicants.',
 'Pair with university aid; AKF expects multi-source funding.',
 'Country-office application + university admission letter.',
 'Contact your country AKF office by December.',
 '50% loan repayment obligation post-graduation.',
 'AKF half-grant half-loan funding for masters/PhD from select developing countries.', true, '2026-04-26'),

('Australia Awards Scholarships', 'Australian Government, DFAT', 'Australia', 'https://www.dfat.gov.au/people-to-people/australia-awards/scholarships',
 'full_ride', 'Full tuition + return air travel + establishment allowance + living + health + academic support', 80000, '2-4 years', true, ARRAY['government','development'],
 ARRAY['masters','phd','diploma'], ARRAY['any'],
 2.9, 4.0, 6.5, 84, NULL,
 'IELTS 6.5 / TOEFL 84 (varies by country)', 'Specific bilateral partner nations in Indo-Pacific', ARRAY['Indonesia','Mongolia','Timor-Leste','Pakistan','Vietnam','Philippines','Bangladesh'], 'Country-specific (e.g., 18+ Timor-Leste)',
 false, true, false,
 'annual', true, 2, true, true, 'Free', 'OASIS portal',
 'Selective','Medium','Country-specific quotas (e.g., 50% public sector in Mongolia). Mandatory home return for 2 years.',
 'Mid-career professional from a partner country with clear career advancement plan.',
 'Without country-specific eligibility, ineligible. Allocations go heavily to public sector in some markets.',
 ARRAY['grad','australia','government','home_return'],
 'Comprehensive package including academic support and reintegration upon return.',
 'Match your application to your country allocation priorities (often public sector).',
 'Country-specific OASIS application, 2 recommenders, employer support letter.',
 'Check your country Australia Awards page for opening dates.',
 '2-year mandatory home return enforced through visa.',
 'Australian government funds masters/PhD/diploma for mid-career professionals from partner Indo-Pacific nations.', true, '2026-04-26'),

('Bolashak International Scholarship', 'Center for International Programs (Kazakhstan)', 'Multiple (top global universities)', 'https://bolashak.gov.kz/',
 'full_ride', 'Full tuition + monthly allowance + travel + insurance + visa', 75000, '2-4 years', false, ARRAY['government'],
 ARRAY['undergraduate','masters','phd'], ARRAY['stem','medicine','engineering','public_policy','it'],
 3.0, 4.0, 5.5, 46, NULL,
 'IELTS 5.5 / TOEFL 46 / HSK 4 / KAZTEST B1', 'Kazakhstan citizens only', ARRAY['Kazakhstan'], 'Medical workers min. 1 year experience',
 false, false, false,
 'annual', true, 2, true, true, 'Free', 'bolashak.gov.kz',
 'Selective','High','Mandatory return to Kazakhstan to work in priority sectors. University admission required first.',
 'Ambitious Kazakh applicant targeting strategic disciplines (STEM, medicine, public administration).',
 'Below 3.0/4.0 GPA or no prior university admission letter = ineligible.',
 ARRAY['undergrad','grad','kazakhstan','government'],
 'Kazakhstan flagship program - largest funder of Kazakh students abroad.',
 'Match your discipline to the year priority list (changes annually).',
 'University admission letter, IELTS/TOEFL, KAZTEST, motivation letter.',
 'Get university admission first, then submit Bolashak application.',
 'Strict mandatory home-return contract enforced.',
 'Kazakh government scholarship for full-degree study abroad in priority sectors.', true, '2026-04-26'),

('Kazakhstan Government Scholarship for Foreigners', 'Ministry of Education and Science of Kazakhstan', 'Kazakhstan', 'https://enic-kazakhstan.edu.kz/',
 'tuition_only', 'Full tuition + monthly stipend (housing and flights not covered)', 8000, '4 years (UG) / 2 years (Masters) / 3 years (PhD)', true, ARRAY['government'],
 ARRAY['undergraduate','masters','phd'], ARRAY['any'],
 3.0, 4.0, 5.5, 46, NULL,
 'IELTS 5.5 / TOEFL 46 / DSH B2 / HSK 4', 'Foreign citizens including ethnic Kazakhs abroad', ARRAY['any'], 'No specific limit',
 false, false, false,
 'annual', true, 2, false, true, 'Free', 'Embassy / Ministry portal',
 'Selective','Low','Quota system per country. UG requires Good diploma; MA/PhD requires GPA >3.0.',
 'Cost-conscious applicant interested in Kazakhstan as study destination.',
 'Coverage excludes housing and flights - budget for $3-5k/year out of pocket.',
 ARRAY['undergrad','grad','kazakhstan','partial'],
 'Affordable degree from a regional Central Asian hub university.',
 'Apply via your country Kazakh embassy with quota allocation.',
 'Transcripts, language test, motivation letter, embassy nomination.',
 'Contact Kazakh embassy by April for September intake.',
 'Housing and flights are NOT covered.',
 'Kazakhstan tuition-only scholarship for foreign UG/Masters/PhD students.', true, '2026-04-26'),

('University of Central Asia (UCA) Scholarships', 'University of Central Asia / Aga Khan Development Network', 'Kazakhstan / Kyrgyzstan / Tajikistan', 'https://www.ucentralasia.org/',
 'partial', 'Up to 95% tuition subsidy on fixed $5,000 tuition + need-based housing/living aid', 20000, '4 years', true, ARRAY['need_based','merit'],
 ARRAY['undergraduate'], ARRAY['economics','communications','engineering','earth_environmental_sciences'],
 NULL, 4.0, 6.0, 79, NULL,
 'English medium of instruction; IELTS 6.0 / TOEFL 79 typical', 'Tajikistan, Kyrgyzstan, Kazakhstan citizens (limited regional and global seats)', ARRAY['Tajikistan','Kyrgyzstan','Kazakhstan'], 'High school graduates',
 true, false, false,
 'annual', true, 2, false, false, 'Free', 'UCA admissions portal',
 'Selective','Medium','Strong applicants need exceptional admissions test, ORT Gold, or Olympiad first place. Subsidies are need-tested up to 95%.',
 'High-performing Central Asian student seeking US-style undergrad without leaving the region.',
 'Without ORT Gold, top admissions test, or Olympiad placement, financial aid is reduced.',
 ARRAY['undergrad','central_asia','need_based','english_medium'],
 'English-medium liberal arts curriculum on Aga Khan-built campuses in Khorog, Naryn, Tekeli.',
 'Lead with admissions test performance - academic merit drives the subsidy ladder.',
 'Admissions test prep, transcripts, motivation letter.',
 'Register for UCA admissions test (held annually in spring).',
 'Subsidies are means-tested - things like ORT Gold strengthen the merit case.',
 'Aga Khan-built liberal arts university serving Tajikistan, Kyrgyzstan, Kazakhstan with up to 95% tuition aid.', true, '2026-04-26');
