
INSERT INTO public.scholarships (
  scholarship_name, provider_name, host_country, official_url,
  coverage_type, award_amount_text, estimated_total_value_usd, duration_text, renewable, award_type,
  target_degree_level, target_fields,
  min_gpa, gpa_scale, min_ielts, min_toefl, min_sat,
  language_requirements, citizenship_requirements, eligible_countries, age_limit,
  financial_need_required, leadership_required, extracurricular_required,
  deadline_type, essay_required, recommendation_letters_required, interview_required,
  separate_application_required, application_fee_text, application_platform,
  selectivity_level, effort_level, effort_reason,
  ideal_candidate_profile, weak_candidate_warning,
  best_for_tags, why_this_fits, how_to_win, what_to_prepare_first, next_step, risk_note,
  eligibility_requirements, verified, last_verified_date
) VALUES

-- DAAD Development-Related Postgraduate Courses (Germany)
('DAAD Development-Related Postgraduate Courses', 'DAAD – German Academic Exchange Service', 'Germany', 'https://www2.daad.de/deutschland/stipendium/datenbank/',
 'full_ride', 'Full tuition + €934/month living stipend + travel allowance + health insurance', 38000, '1–2 years', false, ARRAY['merit','government'],
 ARRAY['masters'], ARRAY['engineering','economics','agriculture','public health','environmental','social sciences'],
 3.0, 4.0, 6.0, 79, NULL,
 'IELTS 6.0 / TOEFL iBT 79 / German B2 — varies per program', 'Citizens of developing and threshold countries (Africa, Asia, Central Asia, Latin America)', ARRAY['any'], 'No strict age limit; 2+ years work experience preferred',
 false, false, false,
 'annual', true, 2, false, true, 'Free', 'DAAD Portal (funding.daad.de)',
 'Selective', 'Medium', 'Requires finding a German host institution, contacting the program directly, and submitting a development-focused statement of purpose through the DAAD portal.',
 'Professional or recent graduate from a developing country with a clear link between proposed study and home-country needs.',
 'Generic statement of purpose not tied to development impact; no prior contact with a German host institution.',
 ARRAY['grad','germany','government','developing_countries'],
 'German public universities charge little to no tuition — DAAD adds a living stipend on top, making total cost near zero.',
 'Shortlist 2–3 German programs, email the program coordinator or professor, then apply through the DAAD portal with a development-focused SoP.',
 'Translated transcripts, development-impact statement of purpose, two academic references, program correspondence.',
 'Contact your target German department directly before submitting — program awareness from the institution strengthens your application.',
 'Language requirements vary: some programs require German B2, others are English-medium. Confirm per program before applying.',
 'DAAD funds postgraduate study in Germany for citizens of developing countries in fields with direct development relevance.', true, '2026-04-27'),

-- MEXT Research Student (Japan)
('MEXT Japanese Government Scholarship – Research Student', 'Ministry of Education, Culture, Sports, Science and Technology (Japan)', 'Japan', 'https://www.mext.go.jp/en/policy/education/highered/title02/detail02/sdetail02/1373897.htm',
 'full_ride', 'Full tuition + ¥143,000–145,000/month stipend (~$950) + return airfare', 48000, '1.5–3 years (research student → degree)', false, ARRAY['merit','government'],
 ARRAY['masters','phd','research'], ARRAY['any'],
 NULL, 4.0, 5.5, 72, NULL,
 'Japanese or English depending on supervisor agreement; JLPT not always required but helpful', 'Any nationality; applied through Japanese Embassy in home country', ARRAY['any'], 'Under 35 for most categories',
 false, false, false,
 'annual', true, 2, true, true, 'Free', 'Japanese Embassy in home country',
 'Selective', 'High', 'Two stages: pass Embassy screening, then secure formal acceptance from a Japanese professor before MEXT confirms funding.',
 'Strong academic record with a specific research plan aligned to a Japanese professor''s lab; genuine interest in working in Japan.',
 'No Japanese professor who formally agrees to supervise you — the application rarely advances past Embassy stage without this.',
 ARRAY['grad','japan','government','research','full_ride'],
 'Japan invests heavily in international researchers; stipend covers living costs comfortably with no additional funding needed.',
 'Find 2–3 Japanese professors whose research matches yours, email them with your research plan, secure one acceptance, then apply through the Embassy.',
 'Research proposal, academic transcripts, two recommendation letters, and a signed pre-acceptance letter from a Japanese professor.',
 'Start professor outreach 6+ months before the Embassy deadline in your country.',
 'Language of instruction varies by lab — confirm whether your supervisor''s group operates in English or Japanese.',
 'Full funding for international research students in Japanese graduate programs; includes stipend, tuition, and return flights.', true, '2026-04-27'),

-- MEXT Undergraduate (Japan)
('MEXT Japanese Government Scholarship – Undergraduate', 'Ministry of Education, Culture, Sports, Science and Technology (Japan)', 'Japan', 'https://www.mext.go.jp/en/policy/education/highered/title02/detail02/sdetail02/1373878.htm',
 'full_ride', 'Full tuition + ¥117,000/month stipend (~$780) + return airfare', 45000, '5 years (1-year Japanese language prep + 4-year degree)', false, ARRAY['merit','government'],
 ARRAY['undergraduate'], ARRAY['any'],
 NULL, 4.0, NULL, NULL, NULL,
 'Japanese language required by graduation; first year at Japanese language school is mandatory', 'Any nationality; Embassy recommendation route or university recommendation route', ARRAY['any'], 'Must be under 25 at time of application',
 false, false, false,
 'annual', true, 2, true, true, 'Free', 'Japanese Embassy in home country',
 'Selective', 'High', 'Embassy exam (written + interview) is competitive; one full year of Japanese language training required before university placement.',
 'Academically strong high school graduate willing to commit to full Japanese-language immersion for 5 years.',
 'No genuine commitment to learning Japanese — most MEXT undergraduate programs are taught entirely in Japanese.',
 ARRAY['undergrad','japan','government','full_ride','language_immersion'],
 'A complete undergraduate degree in Japan — fully funded, including a preparatory language year.',
 'Prepare strong secondary school results, apply through your Embassy, and demonstrate genuine interest in Japanese language and culture in your interview.',
 'High school transcripts and national exam results, two teacher recommendations, personal essay on motivation.',
 'Contact your local Japanese Embassy 12+ months before the deadline — timing and process varies by country.',
 'The 5-year commitment includes a mandatory Japanese language year — not appropriate if you want an English-taught degree.',
 'MEXT undergraduate scholarship for high school graduates to complete a full degree in Japan, including one preparatory language year.', true, '2026-04-27'),

-- Swiss Government Excellence Scholarships
('Swiss Government Excellence Scholarships (ESKAS)', 'Swiss Confederation – State Secretariat for Education (SERI)', 'Switzerland', 'https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html',
 'full_ride', 'CHF 1,920/month + tuition waiver + health insurance + accommodation supplement', 55000, '1–3 years', false, ARRAY['merit','government'],
 ARRAY['masters','phd','research'], ARRAY['any'],
 NULL, 4.0, 7.0, 100, NULL,
 'Language per host institution (English, German, French, or Italian)', 'Citizens of ESKAS-eligible countries (Central Asia, South/Southeast Asia, Africa, Latin America — check annually)', ARRAY['any'], 'Flexible; research/PhD: no strict limit',
 false, false, false,
 'annual', true, 2, false, true, 'Free', 'Swiss Embassy or national scholarship authority in home country',
 'Selective', 'Medium', 'Requires a confirmed Swiss host professor or institution before applying; applied through Swiss Embassy.',
 'Researcher or postgraduate with strong academic record and a Swiss host institution that has agreed to accept them.',
 'No prior contact with a Swiss host institution; generic applications without a focused research or study plan.',
 ARRAY['grad','switzerland','government','research','europe'],
 'Switzerland has no tuition at public universities; the stipend covers living costs in a high-cost country.',
 'Identify a Swiss professor whose research matches yours, secure informal acceptance, then apply through the Swiss Embassy in your country.',
 'Host institution confirmation, research CV, research or study plan, two recommendation letters.',
 'Check ESKAS eligibility for your passport country — not all nationalities are currently eligible.',
 'Switzerland is expensive; confirm the stipend is sufficient for your specific city before committing.',
 'Swiss Government scholarships for foreign researchers and postgraduates to study or conduct research at Swiss institutions.', true, '2026-04-27'),

-- Italian Government Scholarship (MAECI)
('Italian Government Scholarship – MAECI', 'Italian Ministry of Foreign Affairs and International Cooperation', 'Italy', 'https://studyinitaly.esteri.it/',
 'partial', '€900/month stipend + tuition often free at public universities', 12000, '9 months–3 years', false, ARRAY['merit','government'],
 ARRAY['undergraduate','masters','phd'], ARRAY['any'],
 NULL, 4.0, 6.0, 80, NULL,
 'Italian B2 required for most programs; some English-medium programs available at Italian universities', 'Non-EU citizens; varies by bilateral agreement with home country', ARRAY['any'], 'Under 28 for bachelor; under 30 for master; under 40 for PhD',
 false, false, false,
 'annual', true, 2, false, true, 'Free', 'Universitaly portal (universitaly.it) or Italian Embassy',
 'Moderate', 'Medium', 'Applied through the Italian Embassy; language test required for Italian-medium programs; program selection via Universitaly portal.',
 'Student with genuine interest in Italian culture, design, architecture, or art — Italy''s strongest academic competitive advantage.',
 'Weak Italian language skills for Italian-medium programs; no clear academic or cultural motivation.',
 ARRAY['undergrad','grad','italy','europe','government','arts','architecture'],
 'Italian public universities have some of the lowest tuition fees in Europe; stipend covers a significant portion of living costs.',
 'Apply through your Italian Embassy and select programs on Universitaly; start Italian language preparation as soon as possible.',
 'Transcripts, motivation letter, Italian language certificate if available, two references.',
 'Apply 6+ months ahead; Italian B2 language preparation takes 6–12 months from zero.',
 'Not all Italian university programs are in English — confirm language of instruction for your specific course before applying.',
 'Italian government scholarships for non-EU citizens to study at Italian universities at all degree levels.', true, '2026-04-27'),

-- Holland Scholarship (Netherlands)
('Holland Scholarship', 'Dutch Universities and Nuffic (Netherlands)', 'Netherlands', 'https://www.studyinholland.nl/scholarships/holland-scholarship',
 'partial', '€5,000 one-time grant toward first-year costs', 5500, 'One-time (first year only)', false, ARRAY['merit'],
 ARRAY['undergraduate','masters'], ARRAY['any'],
 NULL, 4.0, 6.0, 80, NULL,
 'IELTS 6.0+ or equivalent; varies by Dutch program', 'Non-EEA/EU citizens only; citizenship must be outside the European Economic Area', ARRAY['any'], 'No age limit',
 false, false, false,
 'annual', true, 1, false, false, 'Free', 'Participating Dutch university application portal',
 'Moderate', 'Low', 'Applied through the specific Dutch university; a short motivation letter is typically the main extra requirement.',
 'International student with a confirmed Dutch university offer who needs partial financial support for first-year costs.',
 'EEA/EU citizens are ineligible; the scholarship does not cover full tuition or living costs.',
 ARRAY['undergrad','grad','netherlands','europe','partial'],
 'The Netherlands has an unusually large number of English-medium bachelor and master programs for a non-English-speaking country.',
 'Apply for Dutch university admission first, then apply for the Holland Scholarship through that same university — it is not a separate process.',
 'Motivation letter explaining your choice of the Netherlands and program; English proficiency certificate.',
 'Check which Dutch universities participate in the Holland Scholarship before applying — not all do.',
 'The €5,000 grant is a contribution, not full funding — you need additional resources for tuition and living costs.',
 '€5,000 one-time grant for non-EEA international students admitted to a Dutch bachelor or master program.', true, '2026-04-27'),

-- Lester B. Pearson (University of Toronto, undergrad)
('Lester B. Pearson International Scholarship', 'University of Toronto', 'Canada', 'https://future.utoronto.ca/finances/awards/lester-b-pearson-international-scholarship/',
 'full_ride', 'Full tuition + books + incidental fees + four years of living expenses (~CAD $70,000/year)', 210000, '4 years', true, ARRAY['merit','leadership'],
 ARRAY['undergraduate'], ARRAY['any'],
 NULL, 4.0, 6.5, 100, NULL,
 'IELTS 6.5+ or TOEFL 100+ (UofT standard)', 'Non-Canadian citizens completing secondary school and applying to UofT', ARRAY['any'], 'Must be completing high school at time of application',
 false, true, true,
 'annual', true, 2, true, true, 'CAD $180 UofT application fee', 'UofT admission portal + Pearson nomination',
 'Highly Selective', 'High', 'Your high school must nominate you — UofT accepts 2 nominees per school. Around 37 awards made globally per year.',
 'Exceptional high school student with top grades, demonstrated leadership impact, and a clear sense of purpose.',
 'Cannot apply without a school nomination; students without documented leadership or community impact are rarely selected.',
 ARRAY['undergrad','canada','full_ride','leadership','merit'],
 'One of the most prestigious international undergraduate scholarships in North America — four-year full ride at a globally ranked university.',
 'Speak with your school principal at the start of your final year to secure a nomination; UofT admission application is also required separately.',
 'Top secondary school results, evidence of leadership and community contribution, school principal nomination, two teacher references.',
 'Nominations open each fall — inform your school counselor early; the school nomination is a hard requirement you cannot bypass.',
 'Only ~37 scholarships awarded globally per year; UofT admission (required separately) is also competitive for international applicants.',
 'Four-year full scholarship for exceptional international high school graduates to study at the University of Toronto.', true, '2026-04-27'),

-- Taiwan ICDF
('Taiwan ICDF International Higher Education Scholarship', 'Taiwan International Cooperation and Development Fund', 'Taiwan', 'https://www.icdf.org.tw/ct.asp?xItem=12706&CtNode=30316&mp=2',
 'full_ride', 'Full tuition + NTD 15,000/month (~$470) stipend + round-trip airfare + health insurance', 30000, '2–4 years', false, ARRAY['merit','government'],
 ARRAY['undergraduate','masters','phd'], ARRAY['any'],
 3.0, 4.0, 5.5, 80, NULL,
 'IELTS 5.5 / TOEFL iBT 80 or equivalent English proficiency certificate', 'Citizens of Taiwan ICDF partner countries (Central America, Pacific Islands, parts of Africa and Asia — check list each year)', ARRAY['any'], 'No strict age limit',
 false, false, false,
 'annual', true, 2, false, false, 'Free', 'Taiwan ICDF online application portal',
 'Moderate', 'Medium', 'Requires matching to a Taiwanese university program and submitting a study plan; country eligibility determines access.',
 'Student from an ICDF partner country with a clear academic plan, interest in Taiwan, and willingness to study in a competitive environment.',
 'Non-partner countries; weak study plan not connected to Taiwan ICDF development priorities.',
 ARRAY['undergrad','grad','taiwan','government','developing_countries'],
 'Taiwan offers strong English-medium programs in STEM and business; cost of living is significantly lower than US or European alternatives.',
 'Confirm your country is on the ICDF partner list, select your Taiwanese university and program, then submit via the ICDF portal.',
 'IELTS/TOEFL certificate, transcripts, motivation letter, two recommendations, study plan.',
 'Verify your country is on the ICDF partner list first — spending time applying without eligibility is wasted.',
 'Partner country list changes annually — confirm eligibility each application year.',
 'Taiwan ICDF scholarship for citizens of partner countries to study at Taiwanese universities at undergraduate, master, or doctoral level.', true, '2026-04-27'),

-- KAIST International Scholarship (Korea)
('KAIST International Student Scholarship', 'KAIST – Korea Advanced Institute of Science and Technology', 'South Korea', 'https://admission.kaist.ac.kr/intl-graduate/',
 'full_ride', 'Full tuition + KRW 350,000–600,000/month living allowance (~$250–$450)', 35000, '2–4 years', true, ARRAY['merit'],
 ARRAY['undergraduate','masters','phd'], ARRAY['engineering','science','technology','mathematics'],
 3.5, 4.0, 6.5, 90, NULL,
 'IELTS 6.5 or TOEFL 90+; all KAIST programs conducted in English', 'Non-Korean citizens admitted to KAIST', ARRAY['any'], 'No age limit',
 false, false, false,
 'annual', true, 2, false, false, 'Free (after admission)', 'KAIST admission portal (admission.kaist.ac.kr)',
 'Selective', 'Medium', 'The scholarship is awarded automatically upon admission — the challenge is gaining admission to KAIST itself.',
 'Strong STEM background, competitive transcripts and test scores; clear research interest for graduate applicants.',
 'Non-STEM applicants; below-average academic record in science or engineering.',
 ARRAY['undergrad','grad','korea','stem','full_ride','automatic'],
 'KAIST is one of Asia''s top technical universities; most admitted international students receive full funding automatically.',
 'Invest all your effort in a strong KAIST admission application — the scholarship follows admission.',
 'Mathematics and science transcripts, research proposal or interest statement (graduate), two academic references.',
 'Apply 8+ months ahead; KAIST admission is competitive for international STEM applicants.',
 'GKS scholarship (also Korea) covers a broader field range — KAIST is STEM only.',
 'KAIST awards full tuition and a living allowance to most admitted international students in science and engineering.', true, '2026-04-27'),

-- Singapore International Graduate Award (SINGA)
('Singapore International Graduate Award (SINGA)', 'A*STAR, NUS, NTU, SUTD', 'Singapore', 'https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa',
 'full_ride', 'Full NUS/NTU/SUTD tuition + SGD 2,000–2,500/month stipend (~$1,500–$1,850)', 100000, '4 years (PhD)', false, ARRAY['merit'],
 ARRAY['phd'], ARRAY['engineering','biomedical','science','technology'],
 3.5, 4.0, 6.5, 90, NULL,
 'IELTS 6.5 / TOEFL 90+; all research conducted in English', 'Any nationality; open to all international students', ARRAY['any'], 'No age limit',
 false, false, false,
 'annual', true, 3, true, true, 'Free', 'SINGA application portal (application.singa.edu.sg)',
 'Selective', 'High', 'Strong research background required; interview with a Singapore research supervisor is a key selection step.',
 'STEM graduate with meaningful research experience (publications, thesis, or lab work) seeking a PhD in science or engineering.',
 'No genuine research experience; applying without first contacting potential supervisors.',
 ARRAY['phd','singapore','stem','research','full_ride'],
 'Singapore''s research infrastructure is world-class; A*STAR labs connect directly to industry and publish high-impact work.',
 'Identify 2–3 supervisors at NUS, NTU, or A*STAR whose work matches yours and email them before applying — supervisor match is a selection criterion.',
 'Research CV, publication or project report, GRE scores if required, three academic references.',
 'Email potential supervisors with a specific research pitch before the application deadline.',
 'Singapore is one of Asia''s most expensive cities; the stipend is adequate but not generous by regional standards.',
 'SINGA PhD scholarship at Singapore''s leading research institutions for international students in science and engineering.', true, '2026-04-27'),

-- Czech Government Scholarship
('Czech Government Scholarship – Ministry of Education (MŠMT)', 'Czech Ministry of Education, Youth and Sports', 'Czech Republic', 'https://www.msmt.cz/eu-and-international-affairs/government-scholarships',
 'full_ride', 'Full tuition waiver + CZK 14,000–15,000/month stipend (~$600) + accommodation contribution', 22000, '1–4 years', false, ARRAY['merit','government'],
 ARRAY['undergraduate','masters','phd'], ARRAY['any'],
 NULL, 4.0, NULL, NULL, NULL,
 'Czech B2 for Czech-medium programs; English available for select programs', 'Citizens of eligible countries (Central Asia, Balkans, selected Africa/Asia countries — check annually)', ARRAY['any'], 'Under 26 for bachelor; flexible for graduate',
 false, false, false,
 'annual', true, 2, false, true, 'Free', 'Czech Embassy or MSMT portal in home country',
 'Moderate', 'Medium', 'Applied through the Czech Embassy in your home country; Czech language preparation recommended for Czech-medium programs.',
 'Student with genuine academic interest and willingness to engage with Czech academic culture; language flexibility is important.',
 'No interest in learning Czech; expecting a fully English-medium environment at Czech public universities.',
 ARRAY['undergrad','grad','czech_republic','europe','government'],
 'Czech public universities charge no tuition for Czech-language programs; Prague and Brno have significantly lower living costs than Western Europe.',
 'Apply through your Czech Embassy; confirm whether your target program is Czech or English-medium and prepare language requirements accordingly.',
 'Transcripts, motivation letter, CV, language certificate if available, two references.',
 'Contact your local Czech Embassy 12+ months before the deadline — selection timelines vary significantly by country.',
 'Most Czech public university programs are in Czech; English-medium options are growing but verify your specific program.',
 'Czech Government scholarships for international students at all degree levels at Czech public universities.', true, '2026-04-27'),

-- Lane Kirkland (Poland, Central Asia focus)
('Lane Kirkland Scholarship Programme', 'Polish-American Freedom Foundation', 'Poland', 'https://www.lanekirkland.pl/',
 'partial', 'PLN 4,000/month stipend + university tuition waiver + accommodation contribution', 20000, '1–2 years (master)', false, ARRAY['merit','leadership'],
 ARRAY['masters'], ARRAY['any'],
 NULL, 4.0, 5.5, NULL, NULL,
 'Polish or English per program; many Warsaw and Kraków programs offered in English', 'Citizens of Eastern Partnership and Central Asian countries: Ukraine, Belarus, Moldova, Georgia, Armenia, Azerbaijan, Kazakhstan, Kyrgyzstan, Tajikistan, Uzbekistan', ARRAY['Ukraine','Belarus','Moldova','Georgia','Armenia','Azerbaijan','Kazakhstan','Kyrgyzstan','Tajikistan','Uzbekistan'], 'Under 40',
 false, true, true,
 'annual', true, 2, true, true, 'Free', 'Lane Kirkland Foundation portal (lanekirkland.pl)',
 'Moderate', 'Medium', 'Requires a bachelor degree; selection emphasises civic engagement and professional leadership in your home country.',
 'Emerging professional with a bachelor degree and demonstrated civic or professional leadership who wants graduate education in the EU.',
 'Recent high school graduates without a bachelor degree; applicants without clear leadership or civic engagement documentation.',
 ARRAY['grad','poland','europe','central_asia','leadership'],
 'One of very few scholarships explicitly targeting Central Asian students; Poland has strong English-medium master programs in business, law, and public policy.',
 'Build a leadership portfolio documenting civic or professional impact, apply with a clear plan for what you will do after returning home.',
 'CV documenting leadership experience, two professional or academic references, motivation letter, bachelor diploma and transcripts.',
 'Deadline typically in December for the following academic year — apply well in advance.',
 'Home-country return is expected; the scholarship prioritises applicants who plan to contribute back in their home country.',
 'Polish-American Foundation scholarship for emerging leaders from Eastern Europe and Central Asia to pursue master degrees in Poland.', true, '2026-04-27'),

-- Islamic Development Bank Merit Scholarship
('Islamic Development Bank Merit Scholarship', 'Islamic Development Bank (IsDB)', 'Multiple (worldwide)', 'https://www.isdb.org/scholarships',
 'full_ride', 'Full tuition + monthly stipend + travel allowance + research grant', 45000, '2–4 years', false, ARRAY['merit','need_based','government'],
 ARRAY['masters','phd'], ARRAY['science','technology','engineering','economics','mathematics'],
 3.0, 4.0, 6.0, 79, NULL,
 'IELTS 6.0 or TOEFL iBT 79+; Arabic helpful but not required', 'Citizens of IsDB member countries (57 Muslim-majority nations including Kazakhstan, Kyrgyzstan, Tajikistan, Uzbekistan, Azerbaijan, Turkey, Pakistan, Bangladesh, Nigeria, Indonesia, Egypt, Senegal)', ARRAY['Kazakhstan','Kyrgyzstan','Tajikistan','Uzbekistan','Azerbaijan','Turkey','Indonesia','Pakistan','Bangladesh','Nigeria','Egypt','Morocco'], 'Under 35 for master; under 40 for PhD',
 true, false, false,
 'annual', true, 3, false, true, 'Free', 'IsDB scholarship portal',
 'Selective', 'Medium', 'Two-stage: national IsDB office screening, then international selection committee. Financial need documentation is required.',
 'Student from an IsDB member country with STEM or economics background and documented financial need.',
 'Non-IsDB member country citizens; applicants without financial need documentation.',
 ARRAY['grad','isdb','government','stem','developing_countries','central_asia'],
 'Strong fit for students from Kazakhstan, Kyrgyzstan, Tajikistan, and Uzbekistan — all are IsDB member countries.',
 'Apply through your country''s IsDB national focal point; clearly demonstrate both academic merit and financial need.',
 'Transcripts, financial need documentation, two references, research or study plan, IELTS/TOEFL certificate.',
 'Contact the IsDB focal point at your country''s Ministry of Education to understand the national application route.',
 'STEM fields are prioritised; development relevance of your proposed study strengthens the application.',
 'IsDB Merit Scholarship funds graduate students from member countries to study STEM or economics at recognised universities worldwide.', true, '2026-04-27'),

-- UBC International Leader of Tomorrow Award (Canada, undergrad)
('UBC International Leader of Tomorrow Award', 'University of British Columbia', 'Canada', 'https://you.ubc.ca/financial-planning/scholarships-awards/international-leader-of-tomorrow/',
 'full_ride', 'Full tuition + full living costs based on demonstrated financial need (~CAD $60,000–75,000/year)', 200000, '4 years', true, ARRAY['merit','need_based','leadership'],
 ARRAY['undergraduate'], ARRAY['any'],
 NULL, 4.0, 7.0, 100, NULL,
 'IELTS 7.0 or TOEFL 100+ (UBC standard)', 'International students with demonstrated financial need; open to all nationalities', ARRAY['any'], 'High school graduating year',
 true, true, true,
 'annual', true, 2, true, true, 'CAD $145 UBC application fee', 'UBC admission + supplemental scholarship application',
 'Highly Selective', 'High', 'Holistic evaluation combining academic excellence, financial need, and leadership; considered alongside UBC admission.',
 'High-achieving international student with top grades, demonstrated financial need, and meaningful community leadership.',
 'Applicants without genuine financial need; weak leadership record.',
 ARRAY['undergrad','canada','full_ride','need_based','leadership'],
 'UBC is a top-40 global university; the award covers full demonstrated need without loans, similar to US need-blind schools.',
 'Apply to UBC early and complete the supplemental scholarship application; document leadership and financial need thoroughly and honestly.',
 'Top secondary school results, IELTS/TOEFL, leadership portfolio, financial need documentation, personal essay.',
 'Apply by the early UBC admission deadline — scholarship consideration is tied to your admission application.',
 'Vancouver is among Canada''s most expensive cities; ensure financial need documentation is complete to maximise the award.',
 'UBC''s flagship need-based international undergraduate scholarship, covering full cost of attendance.', true, '2026-04-27'),

-- Heinrich Böll Foundation (Germany)
('Heinrich Böll Foundation Scholarship', 'Heinrich Böll Stiftung (Germany)', 'Germany', 'https://www.boell.de/en/scholarships',
 'partial', '€850/month for bachelor/master + €100 research allowance; €1,200/month for PhD', 18000, '1–3 years', false, ARRAY['merit','leadership'],
 ARRAY['undergraduate','masters','phd'], ARRAY['any'],
 3.0, 4.0, NULL, NULL, NULL,
 'German B2 or English per program; language proficiency tested at application stage', 'Open to all nationalities enrolled (or about to enrol) at a German university', ARRAY['any'], 'No age limit',
 false, false, false,
 'annual', true, 2, true, true, 'Free', 'Böll Foundation online portal (boell.de)',
 'Selective', 'Medium', 'Values-based selection: political engagement, commitment to ecology or feminism, and civic activity matter as much as grades.',
 'Student with strong academic record and documented commitment to ecology, human rights, democracy, or social justice.',
 'Students without evidence of civic or political engagement — academic grades alone are not sufficient.',
 ARRAY['undergrad','grad','germany','foundation','values_based'],
 'German public university tuition is very low or free; the Böll stipend covers living costs and research expenses in Germany.',
 'Document specific alignment with Böll Foundation values in your application essays and prepare for a values-focused interview.',
 'Academic transcripts, political or civic engagement statement, two references, short project or thesis outline.',
 'Apply while enrolled (or about to enrol) at a German university — external pre-entry applications are accepted.',
 'A values-based scholarship — weak alignment with Green, feminist, or social justice politics substantially reduces your chances.',
 'German foundation scholarship for students enrolled at German universities with commitment to ecology, democracy, and social justice.', true, '2026-04-27'),

-- New Zealand Government Scholarships
('New Zealand Government Scholarships (NZGS)', 'New Zealand Ministry of Foreign Affairs and Trade', 'New Zealand', 'https://www.mfat.govt.nz/en/aid-and-development/new-zealand-scholarships/',
 'full_ride', 'Full tuition + NZD 20,000/year living allowance + return airfare + health insurance', 60000, '2–3 years', false, ARRAY['merit','government'],
 ARRAY['masters','phd'], ARRAY['any'],
 NULL, 4.0, 6.5, 90, NULL,
 'IELTS 6.5 / TOEFL 90+ or equivalent', 'Citizens of MFAT partner countries in the Pacific, Southeast Asia, and selected other regions — check annually', ARRAY['any'], '18–40 for most categories',
 false, false, false,
 'annual', true, 2, true, true, 'Free', 'NZ Scholarship online application portal',
 'Selective', 'Medium', 'Country quotas apply; requires demonstrating how NZ study connects to home-country development priorities.',
 'Working professional or graduate with clear development goals and a study plan linked to home-country needs.',
 'Applicants from non-eligible countries; weak connection between proposed study and home-country development.',
 ARRAY['grad','new_zealand','government','pacific','development'],
 'New Zealand has strong programs in agriculture, environmental science, and public health — well matched to Pacific and South Asian development needs.',
 'Frame your study plan explicitly around home-country development priorities; apply through the official MFAT scholarship portal.',
 'Transcripts, development-focused study plan, two references, proof of relevant work experience.',
 'Confirm your country is on the eligible list — Central Asian eligibility is limited.',
 'Pacific Island countries have priority access; competition for other nationalities is for a smaller pool of places.',
 'New Zealand Government scholarships for citizens of development-partner countries to study at NZ universities.', true, '2026-04-27'),

-- Vanier Canada Graduate Scholarships
('Vanier Canada Graduate Scholarships', 'Government of Canada (NSERC / CIHR / SSHRC)', 'Canada', 'https://vanier.gc.ca/',
 'partial', 'CAD $50,000/year for 3 years', 110000, '3 years (PhD)', false, ARRAY['merit','leadership'],
 ARRAY['phd'], ARRAY['any'],
 3.8, 4.0, 7.0, 100, NULL,
 'English or French proficiency per program; IELTS 7.0+ typical', 'Canadian citizens and international students enrolled in a Canadian PhD program', ARRAY['any'], 'No age limit',
 false, true, false,
 'annual', true, 3, false, true, 'Free', 'Canadian university nomination portal',
 'Highly Selective', 'High', 'Must be nominated by a Canadian university — you cannot apply directly; competition is national with limited nominations per institution.',
 'Exceptional doctoral researcher with top academic record and demonstrated leadership outside academic work.',
 'Applicants without a Canadian university nomination; students not yet enrolled in a Canadian PhD program.',
 ARRAY['phd','canada','government','leadership','research'],
 'CAD $50,000/year is among the most generous PhD stipends globally; combined with a strong Canadian research environment.',
 'Gain admission to a Canadian PhD program first, then work closely with your supervisor to submit the Vanier nomination.',
 'Research proposal, academic CV, leadership statements, supervisor support letter, three academic references.',
 'Secure a strong Canadian PhD supervisor before applying — the university nominates you, not the other way around.',
 'Only students already admitted to a Canadian PhD program can be nominated; the university, not the student, submits the nomination.',
 'Vanier scholarships provide CAD $50,000/year for 3 years to exceptional doctoral students at Canadian universities.', true, '2026-04-27'),

-- OSUN / Open Society
('Open Society University Network (OSUN) Scholarships', 'Open Society Foundations / OSUN', 'Multiple (USA, Europe, Central Asia)', 'https://opensocietyuniversitynetwork.org/',
 'full_ride', 'Varies by institution; typically full tuition + living stipend at member campuses', 60000, '1–4 years', false, ARRAY['merit','need_based'],
 ARRAY['undergraduate','masters','phd'], ARRAY['social_sciences','humanities','law','public_policy','human_rights'],
 3.0, 4.0, 6.0, 79, NULL,
 'English proficiency; IELTS 6.0+ typical; varies by OSUN campus', 'Open to all nationalities; historically strong access for post-Soviet and Central Asian students', ARRAY['any'], 'No age limit',
 true, false, false,
 'annual', true, 2, false, true, 'Free', 'Individual OSUN institution portals (CEU, AUCA, Bard, American University of Central Asia)',
 'Selective', 'High', 'OSUN is a network — each member institution has its own application. Applying to multiple campuses is recommended.',
 'Student committed to open society values, human rights, and civic governance — especially from post-Soviet or Global South backgrounds.',
 'Students without clear civic or social justice motivation; STEM applicants will find fewer relevant programs.',
 ARRAY['undergrad','grad','usa','europe','central_asia','social_sciences','values_based'],
 'Historically one of the most accessible fully funded pathways for Central Asian students in social sciences, law, and public policy.',
 'Apply to multiple OSUN network institutions simultaneously — CEU (Vienna), AUCA (Bishkek), and Bard (New York) are the strongest for Central Asian students.',
 'Academic transcripts, personal statement focused on open society or human rights values, two references, writing sample.',
 'Apply to at least 2–3 OSUN institutions simultaneously — competition at each campus is evaluated independently.',
 'Political context in your home country may affect how you articulate values in your personal statement — be genuine but thoughtful.',
 'OSUN network scholarships in social sciences, law, and humanities at institutions across the US, Europe, and Central Asia.', true, '2026-04-27'),

-- KIMEP University (Kazakhstan, English-medium undergrad)
('KIMEP University Merit Scholarship', 'KIMEP University', 'Kazakhstan', 'https://www.kimep.kz/admissions/scholarships/',
 'partial', '25–100% tuition waiver based on GPA', 15000, '4 years', true, ARRAY['merit'],
 ARRAY['undergraduate','masters'], ARRAY['business','law','social_sciences','international_relations'],
 3.0, 4.0, 5.5, 79, NULL,
 'IELTS 5.5 or TOEFL iBT 79+; all programs taught entirely in English', 'Open to Kazakhstani and international students', ARRAY['Kazakhstan','Kyrgyzstan','Uzbekistan','Russia','China','any'], 'No age limit',
 false, false, false,
 'annual', true, 1, false, false, 'Free', 'KIMEP admissions portal (kimep.kz)',
 'Moderate', 'Low', 'GPA-based automatic award; renewed each semester based on academic performance.',
 'Student seeking a fully English-medium business or law degree in Kazakhstan with strong secondary school results.',
 'Students below KIMEP''s admission GPA threshold or with insufficient English proficiency.',
 ARRAY['undergrad','grad','kazakhstan','business','law','english_medium'],
 'KIMEP is Kazakhstan''s only fully English-medium university — strong preparation for international careers without leaving the country.',
 'Apply early to maximise your merit scholarship bracket; maintain a GPA above the threshold each semester to retain it.',
 'High school diploma and transcript, IELTS/TOEFL certificate, motivation letter.',
 'Merit scholarship levels are determined at admission — apply with your strongest academic record.',
 'Covers tuition only; living costs in Almaty are the student''s responsibility.',
 'KIMEP merit scholarship for students in English-medium business, law, and social science programs in Almaty, Kazakhstan.', true, '2026-04-27'),

-- POSCO Asia Fellowship (Korea)
('POSCO Asia Fellowship', 'POSCO TJ Park Foundation', 'South Korea / Multiple', 'https://postf.org/en/business/scholarship',
 'partial', 'KRW 6,000,000–10,000,000/year (approx $4,500–$7,500) + study travel support', 20000, '1–2 years', false, ARRAY['merit','leadership'],
 ARRAY['masters','phd'], ARRAY['any'],
 3.0, 4.0, 6.0, 80, NULL,
 'English proficiency; IELTS 6.0 or equivalent', 'Asian students from China, Japan, Korea, India, Southeast Asia, Central Asia enrolled at Asian universities', ARRAY['China','India','Japan','Vietnam','Indonesia','Philippines','Thailand','Malaysia','Kazakhstan','Kyrgyzstan','Uzbekistan','Mongolia'], 'Under 35',
 false, false, false,
 'annual', true, 2, false, true, 'Free', 'POSCO TJ Park Foundation portal (postf.org)',
 'Moderate', 'Medium', 'Open to students already enrolled at an Asian university; selection focuses on leadership and regional contribution.',
 'Graduate student from an Asian country enrolled at an Asian university, with a clear plan for contributing to regional development.',
 'Students studying outside Asia; applicants with no connection to Asian regional development in their application.',
 ARRAY['grad','korea','asia','leadership','partial'],
 'Korea-backed industrial foundation with a strong alumni network across manufacturing, energy, and technology sectors in Asia.',
 'Apply while enrolled at your Asian university; centre your application on your plan for contributing to Asia''s regional development.',
 'Transcript from current enrollment, leadership statement, two references.',
 'Check the eligibility country list annually — some Central Asian countries are included.',
 'Partial scholarship — will not cover all study costs; you need additional funding for tuition and living expenses.',
 'POSCO TJ Park Foundation scholarship for Asian graduate students demonstrating academic excellence and regional leadership.', true, '2026-04-27');
