-- =============================================================================
-- Application checklists — turn the saved-scholarship list into a workspace
-- =============================================================================
-- The Pipeline page already has a kanban + status flag + notes per saved
-- scholarship. The missing piece for "real workspace" energy is a concrete
-- checklist of WHAT TO DO for each saved application:
--
--   · Required documents (passport, transcripts, certified translations)
--   · Required tests (IELTS 7.0, GRE if applicable, TOEFL alternatives)
--   · Required essays (count, word counts, prompt themes)
--   · Required recommendation letters (count, mix of academic vs professional)
--   · Required portal/system actions (create account on host portal,
--     pay application fee, schedule interview)
--
-- Two tables. Cached, structured, scalable:
--
--   1. public.scholarship_checklists — UNIVERSAL checklist per scholarship.
--      Same items for every applicant. Generated by the AI gateway from
--      the scholarship's already-extracted fields (essay_required,
--      recommendation_letters_required, min_ielts/toefl/sat,
--      citizenship_requirements, eligibility_requirements). Cached forever
--      until schema_version bumps or the scholarship row's last_verified_date
--      moves past the checklist's generated_at.
--
--   2. public.application_tracker.completed_checklist_ids text[]
--      Per-USER progress: which item ids the user has checked off for
--      THEIR application to this scholarship. Lives on the existing
--      application_tracker row so we don't fragment user state.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.scholarship_checklists (
  scholarship_id  uuid        PRIMARY KEY REFERENCES public.scholarships(scholarship_id) ON DELETE CASCADE,
  -- jsonb array of items, each: { id, category, title, detail?, critical?, est_minutes? }
  items           jsonb       NOT NULL,
  -- Schema version on the items shape — bump and old caches regen.
  schema_version  smallint    NOT NULL DEFAULT 1,
  generated_at    timestamptz NOT NULL DEFAULT now(),
  -- For telemetry — same pattern as scholarship_deep_dives.
  cost_estimate_usd numeric(8,4),
  model_tag       text
);

ALTER TABLE public.scholarship_checklists ENABLE ROW LEVEL SECURITY;

-- Public read — checklists are NOT user-specific, they're per-scholarship.
-- Anyone (anon or authed) browsing a scholarship can see the checklist.
CREATE POLICY "Public read checklists"
  ON public.scholarship_checklists FOR SELECT
  USING (true);

-- Service role manages writes (edge function generates them).
CREATE POLICY "Service writes checklists"
  ON public.scholarship_checklists FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- ─── Per-user progress on the checklist ───────────────────────────────
-- Lives on application_tracker so user state stays in one row per
-- (user × scholarship). Defaults to empty array so existing rows
-- gracefully render with nothing checked.
ALTER TABLE public.application_tracker
  ADD COLUMN IF NOT EXISTS completed_checklist_ids text[] NOT NULL DEFAULT ARRAY[]::text[];

-- No new RLS needed — existing application_tracker policies already
-- gate read/write to the row's user_id.
