-- Service-role GRANT audit — fix the 39 public tables with NO service_role
-- access (only postgres). Every edge function using createServiceClient()
-- was silently failing on these tables. Discovered while debugging:
--
--   · scholarship-deadline-cron 500 → "permission denied for table
--     application_tracker"
--   · weekly-nudge-cron 500 → would fail next at application_tracker once
--     the missing-language-column 400 was fixed
--   · enrich-university 404 → embedded select on `applications` silently
--     failed; the function collapsed query error into "University not found"
--
-- The set below was generated by:
--   SELECT c.relname
--   FROM pg_class c JOIN pg_namespace n ON c.relnamespace = n.oid
--   WHERE n.nspname = 'public' AND c.relkind = 'r'
--     AND NOT has_table_privilege('service_role',
--         'public.' || quote_ident(c.relname), 'SELECT')
--   ORDER BY c.relname;
--
-- We also set the default privilege so future tables created in `public`
-- under role postgres automatically grant service_role. Without that, this
-- bug recurs every time a migration adds a table.

-- ─── Per-table grants (the 39 audited holes) ──────────────────────────
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.academy_workshops          TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.aggregated_insights        TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.application_tracker        TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.applications               TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.bookings                   TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.brief_cache                TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.calendar_subscriptions     TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.compass_audits             TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.compass_brands             TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.compass_mentions           TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.compass_prompt_runs        TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.compass_prompts            TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.compass_subscriptions      TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.counselor_messages         TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.counselor_sessions         TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.email_send_log             TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.email_send_state           TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.email_unsubscribe_tokens   TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.engagement_milestones      TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.founding_member_counter    TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.nudge_log                  TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.partner_inquiries          TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.pathway_reports            TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.profiles                   TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.referral_codes             TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.referrals                  TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.saved_searches             TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.scholarships_research_intake TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.shared_briefs              TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.student_documents          TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.student_interactions       TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.student_profiles           TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.student_tasks              TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.subscriptions              TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.suppressed_emails          TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.university_contacts        TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.university_insights        TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.user_roles                 TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.waitlist_emails            TO service_role;

-- ─── Sequences too — INSERTs into id/serial columns need USAGE on the seq ──
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- ─── Default privileges — every future table/sequence created by postgres
--     in `public` will auto-grant service_role. Stops this gap recurring.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO service_role;
